In [169]:
import pandas as pd
import numpy as np
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from tensorflow import keras
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [170]:
player_data = pd.read_csv('/Users/hunter/Desktop/Data_Class/final_project/Data/cleaned_players.csv')

In [171]:
player_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
1,James Milner,CM,4.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Midfield,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20370,Riyad Mahrez,CM,90.0,1,2,0.1,0.1,0.5,2,2,...,1,4,1,1,0,0,2018,25.0,Midfield,PL
20371,Christian Fuchs,LB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,1,0,4,0,0,2018,2.0,Defender,PL
20372,Harry Maguire,CB,90.0,0,0,0.4,0.4,0.0,4,1,...,1,0,2,5,0,0,2018,8.0,Defender,PL
20373,Wes Morgan,CB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,3,0,0,2018,2.5,Defender,PL
20374,Hamza Choudhury,RB,34.0,0,0,0.0,0.0,0.0,1,0,...,1,0,0,4,1,0,2018,-0.5,Defender,PL

In [172]:
forward_data = player_data[player_data['Position Group'] == 'Forward']
forward_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
12,Teemu Pukki,FW,83.0,1,0,0.4,0.4,0.1,3,1,...,1,0,1,1,0,0,2019,15.0,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20353,Harry Kane,FW,90.0,2,0,0.2,0.2,0.0,3,2,...,0,0,0,0,0,0,2018,24.5,Forward,PL
20354,Lucas Moura,LW,74.0,0,1,0.1,0.1,0.0,2,0,...,2,0,0,0,0,0,2018,5.0,Forward,PL
20356,√ârik Lamela,RW,78.0,2,0,1.3,1.3,0.0,2,2,...,2,1,1,2,0,0,2018,26.5,Forward,PL
20361,Son Heung-min,FW,6.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2018,1.0,Forward,PL
20366,Jamie Vardy,FW,90.0,2,0,0.5,0.5,0.3,6,2,...,0,0,0,0,0,0,2018,25.0,Forward,PL

In [173]:
# Groupby player (forward) mean
forward_data_mean = forward_data.groupby(["Player"]).mean()
forward_data_mean.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [174]:
forward_players = forward_data_mean.filter(['Player'], axis=1)
forward_players

Empty DataFrame
Columns: []
Index: [Aaron Connolly, Aaron Lennon, Aaron Mooy, Adam Idah, Adam Lallana, Adam Smith, Adama Traor√©, Ahmed Elmohamady, Ainsley Maitland-Niles, Albian Ajeti, Alex Iwobi, Alex Oxlade-Chamberlain, Alexandre Lacazette, Alexis Mac Allister, Alireza Jahanbakhsh, Allan Saint-Maximin, Andre Gray, Andreas Pereira, Andriy Yarmolenko, Andros Townsend, Andy Carroll, Angel Gomes, Anthony Gordon, Anthony Martial, Anwar El Ghazi, Armando Broja, Arthur Masuaku, Ashley Barnes, Ayoze P√©rez, Ben Chilwell, Ben Osborn, Bernard, Bernardo, Bernardo Silva, Billy Sharp, Borja Bast√≥n, Brandon Williams, Bukayo Saka, Callum Hudson-Odoi, Callum Robinson, Callum Wilson, Calum Chambers, Carlos S√°nchez, Cenk Tosun, Che Adams, Cheikhou Kouyat√©, Chris Wood, Christian Atsu, Christian Benteke, Christian Eriksen, Christian Pulisic, Ciaran Clark, Connor Wickham, Conor Hourihane, Dan Gosling, Daniel James, Daniel Podence, Danny Ings, Danny Rose, Danny Welbeck, David McGoldrick, DeAndre Yedlin, Declan Rice, Dejan Lovren, Dele Alli, Demarai Gray, Dennis Srbeny, Diego Rico, Diogo Dalot, Diogo Jota, Divock Origi, Domingos Quina, Dominic Calvert-Lewin, Dominic Solanke, Douglas Luiz, Dwight Gayle, Dwight McNeil, Eddie Nketiah, Ederson, Emerson Palmieri, Emi Buend√≠a, Emil Krafth, Eric Dier, Ezequiel Schelotto, Fabinho, Faustino Anjorin, Felipe Anderson, Florin Andone, Gabriel Jesus, Georges-K√©vin N'Koudou, Gerard Deulofeu, Giovani Lo Celso, Glenn Murray, Gylfi Sigur√∞sson, Hamza Choudhury, Harry Kane, Harry Wilson, Harry Winks, Harvey Barnes, Henri Lansbury, ...]

[251 rows x 0 columns]

In [175]:
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_var, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

In [176]:
# Create target
y_var = forward_data_mean.SoT
y_var.head()

Player
Aaron Connolly    0.500000
Aaron Lennon      0.166667
Aaron Mooy        0.615385
Adam Idah         0.000000
Adam Lallana      0.000000
Name: SoT, dtype: float64

In [177]:
player_x = forward_data_mean.drop("SoT", axis =1)
player_x.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,Fls,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [178]:
# Create features 
X = player_x
X.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,Fls,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [179]:
X_opt = X.iloc[:,:].values
X_opt

array([[4.93125000e+01, 1.25000000e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [7.36111111e+01, 5.55555556e-02, 5.55555556e-02, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [7.38461538e+01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [4.26969697e+01, 6.06060606e-02, 3.03030303e-02, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [9.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [180]:
y_var = y_var.reset_index().iloc[:,1:].values

In [181]:
# Test if features are siginiicant 
trimmed_X = backwardElimination(X_opt, 0.05)
trimmed_X

array([[1.25000000e-01, 0.00000000e+00, 1.43750000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [5.55555556e-02, 5.55555556e-02, 3.88888889e-01, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [0.00000000e+00, 0.00000000e+00, 1.38461538e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [6.06060606e-02, 3.03030303e-02, 1.09090909e+00, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [182]:
# Split our preprocessed data into our features and target arrays
y = y_var
X = trimmed_X

In [183]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [184]:
# Create scaler instance
scaler = StandardScaler()

In [185]:
# Fit the scaler
X_scaler = scaler.fit(X_train)

In [186]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [187]:
# Define the linear regression model
lin_reg = LinearRegression()

In [188]:
# Train the model
lin_reg.fit(X_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [189]:
lin_reg.score(X_train, y_train)

-337.30147361201944

In [190]:
lin_reg.score(X_test, y_test)

-399.9549447021703

In [191]:
y_pred = lin_reg.predict(X_test)

In [192]:
y_pred_all = lin_reg.predict(X)

In [193]:
r2_score(y_test, y_pred)

-399.9549447021703

In [194]:
# Define hidden layers
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 50

In [195]:
nn = tf.keras.models.Sequential()

In [196]:
# Hidden layer 1
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [197]:
# Hidden layer 2
nn.add(tf.keras.layers.Dense(units=hidden_layer2, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [198]:
# Output layer
nn.add(tf.keras.layers.Dense(units=1))

In [199]:
# Compile the model
nn.compile(loss="mean_squared_error", optimizer="adam")#, metrics=["accuracy"])

In [200]:
# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 50)                600
_________________________________________________________________
dense_13 (Dense)             (None, 50)                2550
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 51
=================================================================
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________

In [201]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Train on 188 samples
Epoch 1/100
188/188 [==============================] - 1s 4ms/sample - loss: 0.2178
Epoch 2/100
188/188 [==============================] - 0s 148us/sample - loss: 0.1280
Epoch 3/100
188/188 [==============================] - 0s 138us/sample - loss: 0.0677
Epoch 4/100
188/188 [==============================] - 0s 146us/sample - loss: 0.0464
Epoch 5/100
188/188 [==============================] - 0s 198us/sample - loss: 0.0394
Epoch 6/100
188/188 [==============================] - 0s 147us/sample - loss: 0.0314
Epoch 7/100
188/188 [==============================] - 0s 151us/sample - loss: 0.0258
Epoch 8/100
188/188 [==============================] - 0s 166us/sample - loss: 0.0237
Epoch 9/100
188/188 [==============================] - 0s 134us/sample - loss: 0.0224
Epoch 10/100
188/188 [==============================] - 0s 138us/sample - loss: 0.0211
Epoch 11/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0199
Epoch 12/100
188/188 [==============================] - 0s 119us/sample - loss: 0.0187
Epoch 13/100
188/188 [==============================] - 0s 148us/sample - loss: 0.0175
Epoch 14/100
188/188 [==============================] - 0s 139us/sample - loss: 0.0167
Epoch 15/100
188/188 [==============================] - 0s 132us/sample - loss: 0.0161
Epoch 16/100
188/188 [==============================] - 0s 148us/sample - loss: 0.0155
Epoch 17/100
188/188 [==============================] - 0s 145us/sample - loss: 0.0149
Epoch 18/100
188/188 [==============================] - 0s 134us/sample - loss: 0.0142
Epoch 19/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0137
Epoch 20/100
188/188 [==============================] - 0s 154us/sample - loss: 0.0135
Epoch 21/100
188/188 [==============================] - 0s 159us/sample - loss: 0.0128
Epoch 22/100
188/188 [==============================] - 0s 168us/sample - loss: 0.0125
Epoch 23/100
188/188 [==============================] - 0s 170us/sample - loss: 0.0122
Epoch 24/100
188/188 [==============================] - 0s 117us/sample - loss: 0.0117
Epoch 25/100
188/188 [==============================] - 0s 144us/sample - loss: 0.0113
Epoch 26/100
188/188 [==============================] - 0s 143us/sample - loss: 0.0110
Epoch 27/100
188/188 [==============================] - 0s 140us/sample - loss: 0.0108
Epoch 28/100
188/188 [==============================] - 0s 120us/sample - loss: 0.0106
Epoch 29/100
188/188 [==============================] - 0s 163us/sample - loss: 0.0100
Epoch 30/100
188/188 [==============================] - 0s 128us/sample - loss: 0.0098
Epoch 31/100
188/188 [==============================] - 0s 128us/sample - loss: 0.0095
Epoch 32/100
188/188 [==============================] - 0s 138us/sample - loss: 0.0092
Epoch 33/100
188/188 [==============================] - 0s 122us/sample - loss: 0.0089
Epoch 34/100
188/188 [==============================] - 0s 144us/sample - loss: 0.0086
Epoch 35/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0084
Epoch 36/100
188/188 [==============================] - 0s 138us/sample - loss: 0.0081
Epoch 37/100
188/188 [==============================] - 0s 124us/sample - loss: 0.0078
Epoch 38/100
188/188 [==============================] - 0s 132us/sample - loss: 0.0076
Epoch 39/100
188/188 [==============================] - 0s 129us/sample - loss: 0.0074
Epoch 40/100
188/188 [==============================] - 0s 109us/sample - loss: 0.0071
Epoch 41/100
188/188 [==============================] - 0s 137us/sample - loss: 0.0070
Epoch 42/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0067
Epoch 43/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0064
Epoch 44/100
188/188 [==============================] - 0s 136us/sample - loss: 0.0063
Epoch 45/100
188/188 [==============================] - 0s 126us/sample - loss: 0.0061
Epoch 46/100
188/188 [==============================] - 0s 135us/sample - loss: 0.0058
Epoch 47/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0056
Epoch 48/100
188/188 [==============================] - 0s 122us/sample - loss: 0.0056
Epoch 49/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0052
Epoch 50/100
188/188 [==============================] - 0s 145us/sample - loss: 0.0050
Epoch 51/100
188/188 [==============================] - 0s 133us/sample - loss: 0.0048
Epoch 52/100
188/188 [==============================] - 0s 237us/sample - loss: 0.0046
Epoch 53/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0047
Epoch 54/100
188/188 [==============================] - 0s 127us/sample - loss: 0.0047
Epoch 55/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0044
Epoch 56/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0039
Epoch 57/100
188/188 [==============================] - 0s 101us/sample - loss: 0.0041
Epoch 58/100
188/188 [==============================] - 0s 105us/sample - loss: 0.0037
Epoch 59/100
188/188 [==============================] - 0s 102us/sample - loss: 0.0037
Epoch 60/100
188/188 [==============================] - 0s 120us/sample - loss: 0.0035
Epoch 61/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0033
Epoch 62/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0032
Epoch 63/100
188/188 [==============================] - 0s 105us/sample - loss: 0.0033
Epoch 64/100
188/188 [==============================] - 0s 105us/sample - loss: 0.0032
Epoch 65/100
188/188 [==============================] - 0s 103us/sample - loss: 0.0031
Epoch 66/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0027
Epoch 67/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0027
Epoch 68/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0026
Epoch 69/100
188/188 [==============================] - 0s 101us/sample - loss: 0.0024
Epoch 70/100
188/188 [==============================] - 0s 103us/sample - loss: 0.0023
Epoch 71/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0023
Epoch 72/100
188/188 [==============================] - 0s 99us/sample - loss: 0.0021
Epoch 73/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0021
Epoch 74/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0020
Epoch 75/100
188/188 [==============================] - 0s 101us/sample - loss: 0.0020
Epoch 76/100
188/188 [==============================] - 0s 103us/sample - loss: 0.0019
Epoch 77/100
188/188 [==============================] - 0s 101us/sample - loss: 0.0020
Epoch 78/100
188/188 [==============================] - 0s 102us/sample - loss: 0.0018
Epoch 79/100
188/188 [==============================] - 0s 103us/sample - loss: 0.0017
Epoch 80/100
188/188 [==============================] - 0s 107us/sample - loss: 0.0016
Epoch 81/100
188/188 [==============================] - 0s 100us/sample - loss: 0.0015
Epoch 82/100
188/188 [==============================] - 0s 98us/sample - loss: 0.0014
Epoch 83/100
188/188 [==============================] - 0s 95us/sample - loss: 0.0014
Epoch 84/100
188/188 [==============================] - 0s 97us/sample - loss: 0.0013
Epoch 85/100
188/188 [==============================] - 0s 98us/sample - loss: 0.0013
Epoch 86/100
188/188 [==============================] - 0s 98us/sample - loss: 0.0012
Epoch 87/100
188/188 [==============================] - 0s 101us/sample - loss: 0.0012
Epoch 88/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0012
Epoch 89/100
188/188 [==============================] - 0s 108us/sample - loss: 0.0011
Epoch 90/100
188/188 [==============================] - 0s 145us/sample - loss: 0.0010
Epoch 91/100
188/188 [==============================] - 0s 136us/sample - loss: 9.7464e-04
Epoch 92/100
188/188 [==============================] - 0s 147us/sample - loss: 9.7615e-04
Epoch 93/100
188/188 [==============================] - 0s 152us/sample - loss: 0.0010
Epoch 94/100
188/188 [==============================] - 0s 143us/sample - loss: 9.1138e-04

Epoch 95/100
188/188 [==============================] - 0s 107us/sample - loss: 8.3874e-04
Epoch 96/100
188/188 [==============================] - 0s 102us/sample - loss: 8.6161e-04
Epoch 97/100
188/188 [==============================] - 0s 107us/sample - loss: 8.9273e-04
Epoch 98/100
188/188 [==============================] - 0s 124us/sample - loss: 8.1817e-04
Epoch 99/100
188/188 [==============================] - 0s 408us/sample - loss: 7.2484e-04
Epoch 100/100
188/188 [==============================] - 0s 158us/sample - loss: 7.3989e-04

In [202]:
# Evaluate the model using the test data - mean
#model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")
model_loss = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}")

63/1 - 0s - loss: 0.0067
Loss: 0.009205109018477656

In [203]:
#y_pred.shape
y_pred_all.shape

(251, 1)

In [204]:
#y_pred
y_pred_all

array([[ 5.61356765],
       [ 4.00417625],
       [ 4.87969709],
       [ 4.32259082],
       [ 2.44204872],
       [ 2.14497842],
       [ 6.00281912],
       [ 1.03880101],
       [22.05443385],
       [ 1.12957526],
       [ 7.27176313],
       [ 5.74028633],
       [12.32225324],
       [ 2.74646874],
       [ 4.93389143],
       [ 7.57519706],
       [ 7.24530291],
       [ 2.74108538],
       [ 3.39984127],
       [ 7.21907651],
       [ 3.23877916],
       [ 5.41654783],
       [ 3.66425568],
       [12.20173029],
       [ 8.15669428],
       [ 2.14497842],
       [ 6.8462018 ],
       [ 7.938651  ],
       [11.1449656 ],
       [ 0.67586561],
       [ 3.59672002],
       [ 5.06454537],
       [ 6.90205726],
       [ 9.8318527 ],
       [ 4.22998323],
       [ 2.14497842],
       [ 2.14497842],
       [ 2.75362347],
       [ 5.14623912],
       [ 3.84809383],
       [10.08180071],
       [ 0.67586561],
       [ 2.14497842],
       [ 7.17654461],
       [ 2.95552725],
       [ 2.84611054],
       [10.35371205],
       [ 3.24291825],
       [ 4.80503703],
       [13.20667448],
       [13.59242953],
       [ 2.14497842],
       [ 3.98761865],
       [ 2.14497842],
       [ 2.54836901],
       [ 7.88154894],
       [ 3.50610737],
       [12.407934  ],
       [ 3.24198292],
       [ 4.2669681 ],
       [ 4.95899705],
       [ 0.42490594],
       [ 2.87084922],
       [ 2.14497842],
       [10.36469401],
       [ 5.42819867],
       [ 0.67586561],
       [ 2.03699455],
       [ 2.39173165],
       [ 8.91922997],
       [ 7.49907205],
       [ 1.41042202],
       [ 7.92994267],
       [ 3.90386374],
       [ 3.34795906],
       [ 7.02308375],
       [ 9.82051737],
       [ 4.91263857],
       [-7.88208777],
       [ 1.65527415],
       [ 6.63769013],
       [ 2.87084922],
       [ 2.52479774],
       [ 2.44572358],
       [-0.06737641],
       [ 2.74646874],
       [ 9.8218359 ],
       [ 3.84734829],
       [13.1659222 ],
       [ 4.61511492],
       [10.46925066],
       [ 1.17537427],
       [ 6.22808847],
       [ 7.71752445],
       [ 4.14369853],
       [19.29918087],
       [ 7.32603381],
       [ 2.14497842],
       [ 8.07096076],
       [ 1.41042202],
       [ 7.68450684],
       [ 0.91332117],
       [ 2.50791382],
       [ 1.89723109],
       [ 3.06868428],
       [11.55554195],
       [12.49170485],
       [ 1.65527415],
       [ 9.01399464],
       [ 7.95557963],
       [ 2.14497842],
       [ 8.35401241],
       [15.51762168],
       [11.90013335],
       [ 9.12276743],
       [ 7.44307249],
       [ 7.04892713],
       [ 4.28205212],
       [ 8.41315853],
       [ 2.14497842],
       [ 2.88773314],
       [ 4.39825081],
       [ 2.14497842],
       [ 1.40372299],
       [ 2.14497842],
       [ 7.04953687],
       [ 0.67586561],
       [ 4.04823227],
       [ 7.71150569],
       [ 5.16336865],
       [ 2.87273945],
       [-7.88208777],
       [ 6.71669224],
       [ 9.55186621],
       [10.31087976],
       [ 4.12043322],
       [ 3.39601776],
       [ 5.51957542],
       [ 2.14497842],
       [ 3.87604434],
       [-0.30965047],
       [ 6.41750508],
       [ 2.44572358],
       [ 0.67586561],
       [ 8.96941077],
       [ 2.14497842],
       [ 2.93137158],
       [ 5.50989407],
       [12.51499384],
       [ 6.13673874],
       [-2.76427936],
       [12.55549451],
       [ 0.67586561],
       [ 7.21884522],
       [ 8.41123615],
       [ 2.14497842],
       [ 8.19482059],
       [ 3.99934606],
       [ 2.14497842],
       [ 6.77669152],
       [ 4.74145595],
       [ 2.14497842],
       [ 8.87356523],
       [ 9.91429726],
       [ 6.03858881],
       [ 6.43206919],
       [ 7.62822225],
       [ 4.9976407 ],
       [21.8970341 ],
       [ 4.84315738],
       [ 3.22446656],
       [ 1.51931286],
       [ 5.9445481 ],
       [ 6.77582064],
       [ 5.86184202],
       [ 1.45197308],
       [10.8727585 ],
       [ 9.48135184],
       [ 3.6364951 ],
       [ 6.20190783],
       [ 1.77335742],
       [ 7.33053223],
       [ 4.89899371],
       [ 7.14438765],
       [ 7.99231282],
       [ 9.04367097],
       [ 7.3374468 ],
       [ 2.14497842],
       [ 3.66425568],
       [ 2.90461705],
       [10.17487582],
       [ 6.0011227 ],
       [ 4.00309906],
       [ 2.52479774],
       [ 0.24604622],
       [18.5192877 ],
       [15.34966783],
       [13.38335853],
       [ 2.92339729],
       [ 6.75560417],
       [10.20686595],
       [13.23004948],
       [ 2.14497842],
       [ 1.60933741],
       [ 4.44210566],
       [12.67683043],
       [ 8.32614789],
       [ 0.67996476],
       [ 6.01803815],
       [ 8.66309603],
       [ 7.27474317],
       [ 2.90461705],
       [ 1.16556988],
       [15.52828327],
       [ 2.14497842],
       [ 2.44572358],
       [ 4.14369853],
       [ 2.14497842],
       [21.21272914],
       [ 5.05615883],
       [ 3.24490201],
       [ 4.63073795],
       [14.59107699],
       [ 2.14497842],
       [10.17702609],
       [ 4.91104348],
       [ 8.85786494],
       [ 3.6364951 ],
       [ 1.27735593],
       [11.51941168],
       [13.05030683],
       [ 6.87933057],
       [ 8.66591992],
       [ 4.22233539],
       [ 2.25676447],
       [ 2.14497842],
       [ 8.49124455],
       [ 6.17367255],
       [ 3.62951324],
       [ 9.07484523],
       [ 6.7021144 ],
       [ 8.88142534],
       [ 5.34645031],
       [ 9.07129064],
       [ 9.51866671],
       [ 2.87084922],
       [ 2.73266318],
       [ 3.3942133 ],
       [ 3.80546116],
       [ 3.34795906],
       [ 2.14497842]])

In [205]:
#np.rint(y_pred)
y_pred_all_clean = np.rint(y_pred_all)
y_pred_all_clean

array([[ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 2.],
       [ 2.],
       [ 6.],
       [ 1.],
       [22.],
       [ 1.],
       [ 7.],
       [ 6.],
       [12.],
       [ 3.],
       [ 5.],
       [ 8.],
       [ 7.],
       [ 3.],
       [ 3.],
       [ 7.],
       [ 3.],
       [ 5.],
       [ 4.],
       [12.],
       [ 8.],
       [ 2.],
       [ 7.],
       [ 8.],
       [11.],
       [ 1.],
       [ 4.],
       [ 5.],
       [ 7.],
       [10.],
       [ 4.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 5.],
       [ 4.],
       [10.],
       [ 1.],
       [ 2.],
       [ 7.],
       [ 3.],
       [ 3.],
       [10.],
       [ 3.],
       [ 5.],
       [13.],
       [14.],
       [ 2.],
       [ 4.],
       [ 2.],
       [ 3.],
       [ 8.],
       [ 4.],
       [12.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 0.],
       [ 3.],
       [ 2.],
       [10.],
       [ 5.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 9.],
       [ 7.],
       [ 1.],
       [ 8.],
       [ 4.],
       [ 3.],
       [ 7.],
       [10.],
       [ 5.],
       [-8.],
       [ 2.],
       [ 7.],
       [ 3.],
       [ 3.],
       [ 2.],
       [-0.],
       [ 3.],
       [10.],
       [ 4.],
       [13.],
       [ 5.],
       [10.],
       [ 1.],
       [ 6.],
       [ 8.],
       [ 4.],
       [19.],
       [ 7.],
       [ 2.],
       [ 8.],
       [ 1.],
       [ 8.],
       [ 1.],
       [ 3.],
       [ 2.],
       [ 3.],
       [12.],
       [12.],
       [ 2.],
       [ 9.],
       [ 8.],
       [ 2.],
       [ 8.],
       [16.],
       [12.],
       [ 9.],
       [ 7.],
       [ 7.],
       [ 4.],
       [ 8.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 7.],
       [ 1.],
       [ 4.],
       [ 8.],
       [ 5.],
       [ 3.],
       [-8.],
       [ 7.],
       [10.],
       [10.],
       [ 4.],
       [ 3.],
       [ 6.],
       [ 2.],
       [ 4.],
       [-0.],
       [ 6.],
       [ 2.],
       [ 1.],
       [ 9.],
       [ 2.],
       [ 3.],
       [ 6.],
       [13.],
       [ 6.],
       [-3.],
       [13.],
       [ 1.],
       [ 7.],
       [ 8.],
       [ 2.],
       [ 8.],
       [ 4.],
       [ 2.],
       [ 7.],
       [ 5.],
       [ 2.],
       [ 9.],
       [10.],
       [ 6.],
       [ 6.],
       [ 8.],
       [ 5.],
       [22.],
       [ 5.],
       [ 3.],
       [ 2.],
       [ 6.],
       [ 7.],
       [ 6.],
       [ 1.],
       [11.],
       [ 9.],
       [ 4.],
       [ 6.],
       [ 2.],
       [ 7.],
       [ 5.],
       [ 7.],
       [ 8.],
       [ 9.],
       [ 7.],
       [ 2.],
       [ 4.],
       [ 3.],
       [10.],
       [ 6.],
       [ 4.],
       [ 3.],
       [ 0.],
       [19.],
       [15.],
       [13.],
       [ 3.],
       [ 7.],
       [10.],
       [13.],
       [ 2.],
       [ 2.],
       [ 4.],
       [13.],
       [ 8.],
       [ 1.],
       [ 6.],
       [ 9.],
       [ 7.],
       [ 3.],
       [ 1.],
       [16.],
       [ 2.],
       [ 2.],
       [ 4.],
       [ 2.],
       [21.],
       [ 5.],
       [ 3.],
       [ 5.],
       [15.],
       [ 2.],
       [10.],
       [ 5.],
       [ 9.],
       [ 4.],
       [ 1.],
       [12.],
       [13.],
       [ 7.],
       [ 9.],
       [ 4.],
       [ 2.],
       [ 2.],
       [ 8.],
       [ 6.],
       [ 4.],
       [ 9.],
       [ 7.],
       [ 9.],
       [ 5.],
       [ 9.],
       [10.],
       [ 3.],
       [ 3.],
       [ 3.],
       [ 4.],
       [ 3.],
       [ 2.]])

In [206]:
#for item in y_pred_all_clean:
#    if item <= 0: 
#        item = 0

In [207]:
y_pred_all_clean.shape

(251, 1)

In [208]:
y_pred_all_clean[y_pred_all_clean <= 0] = 0
y_pred_all_clean

array([[ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 2.],
       [ 2.],
       [ 6.],
       [ 1.],
       [22.],
       [ 1.],
       [ 7.],
       [ 6.],
       [12.],
       [ 3.],
       [ 5.],
       [ 8.],
       [ 7.],
       [ 3.],
       [ 3.],
       [ 7.],
       [ 3.],
       [ 5.],
       [ 4.],
       [12.],
       [ 8.],
       [ 2.],
       [ 7.],
       [ 8.],
       [11.],
       [ 1.],
       [ 4.],
       [ 5.],
       [ 7.],
       [10.],
       [ 4.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 5.],
       [ 4.],
       [10.],
       [ 1.],
       [ 2.],
       [ 7.],
       [ 3.],
       [ 3.],
       [10.],
       [ 3.],
       [ 5.],
       [13.],
       [14.],
       [ 2.],
       [ 4.],
       [ 2.],
       [ 3.],
       [ 8.],
       [ 4.],
       [12.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 0.],
       [ 3.],
       [ 2.],
       [10.],
       [ 5.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 9.],
       [ 7.],
       [ 1.],
       [ 8.],
       [ 4.],
       [ 3.],
       [ 7.],
       [10.],
       [ 5.],
       [ 0.],
       [ 2.],
       [ 7.],
       [ 3.],
       [ 3.],
       [ 2.],
       [ 0.],
       [ 3.],
       [10.],
       [ 4.],
       [13.],
       [ 5.],
       [10.],
       [ 1.],
       [ 6.],
       [ 8.],
       [ 4.],
       [19.],
       [ 7.],
       [ 2.],
       [ 8.],
       [ 1.],
       [ 8.],
       [ 1.],
       [ 3.],
       [ 2.],
       [ 3.],
       [12.],
       [12.],
       [ 2.],
       [ 9.],
       [ 8.],
       [ 2.],
       [ 8.],
       [16.],
       [12.],
       [ 9.],
       [ 7.],
       [ 7.],
       [ 4.],
       [ 8.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 7.],
       [ 1.],
       [ 4.],
       [ 8.],
       [ 5.],
       [ 3.],
       [ 0.],
       [ 7.],
       [10.],
       [10.],
       [ 4.],
       [ 3.],
       [ 6.],
       [ 2.],
       [ 4.],
       [ 0.],
       [ 6.],
       [ 2.],
       [ 1.],
       [ 9.],
       [ 2.],
       [ 3.],
       [ 6.],
       [13.],
       [ 6.],
       [ 0.],
       [13.],
       [ 1.],
       [ 7.],
       [ 8.],
       [ 2.],
       [ 8.],
       [ 4.],
       [ 2.],
       [ 7.],
       [ 5.],
       [ 2.],
       [ 9.],
       [10.],
       [ 6.],
       [ 6.],
       [ 8.],
       [ 5.],
       [22.],
       [ 5.],
       [ 3.],
       [ 2.],
       [ 6.],
       [ 7.],
       [ 6.],
       [ 1.],
       [11.],
       [ 9.],
       [ 4.],
       [ 6.],
       [ 2.],
       [ 7.],
       [ 5.],
       [ 7.],
       [ 8.],
       [ 9.],
       [ 7.],
       [ 2.],
       [ 4.],
       [ 3.],
       [10.],
       [ 6.],
       [ 4.],
       [ 3.],
       [ 0.],
       [19.],
       [15.],
       [13.],
       [ 3.],
       [ 7.],
       [10.],
       [13.],
       [ 2.],
       [ 2.],
       [ 4.],
       [13.],
       [ 8.],
       [ 1.],
       [ 6.],
       [ 9.],
       [ 7.],
       [ 3.],
       [ 1.],
       [16.],
       [ 2.],
       [ 2.],
       [ 4.],
       [ 2.],
       [21.],
       [ 5.],
       [ 3.],
       [ 5.],
       [15.],
       [ 2.],
       [10.],
       [ 5.],
       [ 9.],
       [ 4.],
       [ 1.],
       [12.],
       [13.],
       [ 7.],
       [ 9.],
       [ 4.],
       [ 2.],
       [ 2.],
       [ 8.],
       [ 6.],
       [ 4.],
       [ 9.],
       [ 7.],
       [ 9.],
       [ 5.],
       [ 9.],
       [10.],
       [ 3.],
       [ 3.],
       [ 3.],
       [ 4.],
       [ 3.],
       [ 2.]])

In [209]:
y_pred_all_clean.shape

(251, 1)

In [210]:
forward_players['Pred_SoT'] = y_pred_all_clean
forward_players

                Pred_SoT
Player
Aaron Connolly       6.0
Aaron Lennon         4.0
Aaron Mooy           5.0
Adam Idah            4.0
Adam Lallana         2.0
...                  ...
Yoshinori Mut≈ç       3.0
Yves Bissouma        3.0
√ârik Lamela          4.0
√âtienne Capoue       3.0
ƒ∞lkay G√ºndoƒüan       2.0

[251 rows x 1 columns]

In [211]:
pred_SoT_df = forward_players
pred_SoT_df

                Pred_SoT
Player
Aaron Connolly       6.0
Aaron Lennon         4.0
Aaron Mooy           5.0
Adam Idah            4.0
Adam Lallana         2.0
...                  ...
Yoshinori Mut≈ç       3.0
Yves Bissouma        3.0
√ârik Lamela          4.0
√âtienne Capoue       3.0
ƒ∞lkay G√ºndoƒüan       2.0

[251 rows x 1 columns]

In [212]:
pred_SoT_df.to_csv('pred_SoT.csv')

In [213]:
y_pred_nn = nn.predict(X_test_scaled)#X_scaler.transform(X))
y_pred_nn
pd.DataFrame({'y_pred_nn': y_pred_nn[:,0], 'y_test': y_test[:,0]})

    y_pred_nn    y_test
0   -0.035125  0.200000
1    0.636604  1.000000
2    1.035156  0.983051
3    0.548585  0.641026
4    0.118377  0.000000
..        ...       ...
58  -0.050667  0.000000
59   0.575586  0.584615
60  -0.016851  0.000000
61   0.905028  0.833333
62   0.976288  1.000000

[63 rows x 2 columns]