In [117]:
import pandas as pd
import numpy as np
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from tensorflow import keras
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [118]:
player_data = pd.read_csv('/Users/hunter/Desktop/Data_Class/final_project/Data/cleaned_players.csv')

In [119]:
player_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
1,James Milner,CM,4.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Midfield,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20370,Riyad Mahrez,CM,90.0,1,2,0.1,0.1,0.5,2,2,...,1,4,1,1,0,0,2018,25.0,Midfield,PL
20371,Christian Fuchs,LB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,1,0,4,0,0,2018,2.0,Defender,PL
20372,Harry Maguire,CB,90.0,0,0,0.4,0.4,0.0,4,1,...,1,0,2,5,0,0,2018,8.0,Defender,PL
20373,Wes Morgan,CB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,3,0,0,2018,2.5,Defender,PL
20374,Hamza Choudhury,RB,34.0,0,0,0.0,0.0,0.0,1,0,...,1,0,0,4,1,0,2018,-0.5,Defender,PL

In [120]:
forward_data = player_data[player_data['Position Group'] == 'Forward']
forward_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
12,Teemu Pukki,FW,83.0,1,0,0.4,0.4,0.1,3,1,...,1,0,1,1,0,0,2019,15.0,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20353,Harry Kane,FW,90.0,2,0,0.2,0.2,0.0,3,2,...,0,0,0,0,0,0,2018,24.5,Forward,PL
20354,Lucas Moura,LW,74.0,0,1,0.1,0.1,0.0,2,0,...,2,0,0,0,0,0,2018,5.0,Forward,PL
20356,√ârik Lamela,RW,78.0,2,0,1.3,1.3,0.0,2,2,...,2,1,1,2,0,0,2018,26.5,Forward,PL
20361,Son Heung-min,FW,6.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2018,1.0,Forward,PL
20366,Jamie Vardy,FW,90.0,2,0,0.5,0.5,0.3,6,2,...,0,0,0,0,0,0,2018,25.0,Forward,PL

In [121]:
# Groupby player (forward) mean
forward_data_mean = forward_data.groupby(["Player"]).mean()
forward_data_mean.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [122]:
forward_players = forward_data_mean.filter(['Player'], axis=1)
forward_players

Empty DataFrame
Columns: []
Index: [Aaron Connolly, Aaron Lennon, Aaron Mooy, Adam Idah, Adam Lallana, Adam Smith, Adama Traor√©, Ahmed Elmohamady, Ainsley Maitland-Niles, Albian Ajeti, Alex Iwobi, Alex Oxlade-Chamberlain, Alexandre Lacazette, Alexis Mac Allister, Alireza Jahanbakhsh, Allan Saint-Maximin, Andre Gray, Andreas Pereira, Andriy Yarmolenko, Andros Townsend, Andy Carroll, Angel Gomes, Anthony Gordon, Anthony Martial, Anwar El Ghazi, Armando Broja, Arthur Masuaku, Ashley Barnes, Ayoze P√©rez, Ben Chilwell, Ben Osborn, Bernard, Bernardo, Bernardo Silva, Billy Sharp, Borja Bast√≥n, Brandon Williams, Bukayo Saka, Callum Hudson-Odoi, Callum Robinson, Callum Wilson, Calum Chambers, Carlos S√°nchez, Cenk Tosun, Che Adams, Cheikhou Kouyat√©, Chris Wood, Christian Atsu, Christian Benteke, Christian Eriksen, Christian Pulisic, Ciaran Clark, Connor Wickham, Conor Hourihane, Dan Gosling, Daniel James, Daniel Podence, Danny Ings, Danny Rose, Danny Welbeck, David McGoldrick, DeAndre Yedlin, Declan Rice, Dejan Lovren, Dele Alli, Demarai Gray, Dennis Srbeny, Diego Rico, Diogo Dalot, Diogo Jota, Divock Origi, Domingos Quina, Dominic Calvert-Lewin, Dominic Solanke, Douglas Luiz, Dwight Gayle, Dwight McNeil, Eddie Nketiah, Ederson, Emerson Palmieri, Emi Buend√≠a, Emil Krafth, Eric Dier, Ezequiel Schelotto, Fabinho, Faustino Anjorin, Felipe Anderson, Florin Andone, Gabriel Jesus, Georges-K√©vin N'Koudou, Gerard Deulofeu, Giovani Lo Celso, Glenn Murray, Gylfi Sigur√∞sson, Hamza Choudhury, Harry Kane, Harry Wilson, Harry Winks, Harvey Barnes, Henri Lansbury, ...]

[251 rows x 0 columns]

In [123]:
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_var, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

In [124]:
# Create target
y_var = forward_data_mean.TklW
y_var.head()

Player
Aaron Connolly    0.250000
Aaron Lennon      0.888889
Aaron Mooy        1.461538
Adam Idah         3.000000
Adam Lallana      0.230769
Name: TklW, dtype: float64

In [125]:
player_x = forward_data_mean.drop("TklW", axis =1)
player_x.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.153846,0.0,2018.307692,1.230769

In [126]:
# Create features 
X = player_x
X.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.153846,0.0,2018.307692,1.230769

In [127]:
X_opt = X.iloc[:,:].values
X_opt

array([[4.93125000e+01, 1.25000000e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [7.36111111e+01, 5.55555556e-02, 5.55555556e-02, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [7.38461538e+01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [4.26969697e+01, 6.06060606e-02, 3.03030303e-02, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [9.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [128]:
y_var = y_var.reset_index().iloc[:,1:].values

In [129]:
# Test if features are siginiicant 
trimmed_X = backwardElimination(X_opt, 0.05)
trimmed_X

array([[1.25000000e-01, 0.00000000e+00, 1.43750000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [5.55555556e-02, 5.55555556e-02, 3.88888889e-01, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [0.00000000e+00, 0.00000000e+00, 1.38461538e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [6.06060606e-02, 3.03030303e-02, 1.09090909e+00, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [130]:
# Split our preprocessed data into our features and target arrays
y = y_var
X = trimmed_X

In [131]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [132]:
# Create scaler instance
scaler = StandardScaler()

In [133]:
# Fit the scaler
X_scaler = scaler.fit(X_train)

In [134]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [135]:
# Define the linear regression model
lin_reg = LinearRegression()

In [136]:
# Train the model
lin_reg.fit(X_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [137]:
lin_reg.score(X_train, y_train)

-1157.9582738982092

In [138]:
lin_reg.score(X_test, y_test)

-3369.054923220299

In [139]:
y_pred = lin_reg.predict(X_test)

In [140]:
y_pred_all = lin_reg.predict(X)

In [141]:
r2_score(y_test, y_pred)

-3369.054923220299

In [142]:
# Define hidden layers
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 50

In [143]:
nn = tf.keras.models.Sequential()

In [144]:
# Hidden layer 1
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [145]:
# Hidden layer 2
nn.add(tf.keras.layers.Dense(units=hidden_layer2, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [146]:
# Output layer
nn.add(tf.keras.layers.Dense(units=1))

In [147]:
# Compile the model
nn.compile(loss="mean_squared_error", optimizer="adam")#, metrics=["accuracy"])

In [148]:
# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_9 (Dense)              (None, 50)                600
_________________________________________________________________
dense_10 (Dense)             (None, 50)                2550
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 51
=================================================================
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________

In [149]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Train on 188 samples
Epoch 1/100
188/188 [==============================] - 1s 5ms/sample - loss: 0.4667
Epoch 2/100
188/188 [==============================] - 0s 136us/sample - loss: 0.3749
Epoch 3/100
188/188 [==============================] - 0s 107us/sample - loss: 0.3130
Epoch 4/100
188/188 [==============================] - 0s 169us/sample - loss: 0.2745
Epoch 5/100
188/188 [==============================] - 0s 136us/sample - loss: 0.2581
Epoch 6/100
188/188 [==============================] - 0s 112us/sample - loss: 0.2460
Epoch 7/100
188/188 [==============================] - 0s 137us/sample - loss: 0.2338
Epoch 8/100
188/188 [==============================] - 0s 154us/sample - loss: 0.2197
Epoch 9/100
188/188 [==============================] - 0s 134us/sample - loss: 0.2114
Epoch 10/100
188/188 [==============================] - 0s 122us/sample - loss: 0.2033
Epoch 11/100
188/188 [==============================] - 0s 123us/sample - loss: 0.1960
Epoch 12/100
188/188 [==============================] - 0s 105us/sample - loss: 0.1907
Epoch 13/100
188/188 [==============================] - 0s 173us/sample - loss: 0.1866
Epoch 14/100
188/188 [==============================] - 0s 147us/sample - loss: 0.1829
Epoch 15/100
188/188 [==============================] - 0s 160us/sample - loss: 0.1775
Epoch 16/100
188/188 [==============================] - 0s 190us/sample - loss: 0.1732
Epoch 17/100
188/188 [==============================] - 0s 128us/sample - loss: 0.1681
Epoch 18/100
188/188 [==============================] - 0s 143us/sample - loss: 0.1651
Epoch 19/100
188/188 [==============================] - 0s 130us/sample - loss: 0.1611
Epoch 20/100
188/188 [==============================] - 0s 125us/sample - loss: 0.1565
Epoch 21/100
188/188 [==============================] - 0s 110us/sample - loss: 0.1528
Epoch 22/100
188/188 [==============================] - 0s 127us/sample - loss: 0.1504
Epoch 23/100
188/188 [==============================] - 0s 143us/sample - loss: 0.1459
Epoch 24/100
188/188 [==============================] - 0s 166us/sample - loss: 0.1413
Epoch 25/100
188/188 [==============================] - 0s 152us/sample - loss: 0.1391
Epoch 26/100
188/188 [==============================] - 0s 160us/sample - loss: 0.1349
Epoch 27/100
188/188 [==============================] - 0s 162us/sample - loss: 0.1303
Epoch 28/100
188/188 [==============================] - 0s 133us/sample - loss: 0.1254
Epoch 29/100
188/188 [==============================] - 0s 124us/sample - loss: 0.1234
Epoch 30/100
188/188 [==============================] - 0s 159us/sample - loss: 0.1211
Epoch 31/100
188/188 [==============================] - 0s 107us/sample - loss: 0.1157
Epoch 32/100
188/188 [==============================] - 0s 148us/sample - loss: 0.1113
Epoch 33/100
188/188 [==============================] - 0s 135us/sample - loss: 0.1080
Epoch 34/100
188/188 [==============================] - 0s 158us/sample - loss: 0.1056
Epoch 35/100
188/188 [==============================] - 0s 148us/sample - loss: 0.0988
Epoch 36/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0975
Epoch 37/100
188/188 [==============================] - 0s 162us/sample - loss: 0.0922
Epoch 38/100
188/188 [==============================] - 0s 193us/sample - loss: 0.0906
Epoch 39/100
188/188 [==============================] - 0s 146us/sample - loss: 0.0881
Epoch 40/100
188/188 [==============================] - 0s 108us/sample - loss: 0.0841
Epoch 41/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0813
Epoch 42/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0795
Epoch 43/100
188/188 [==============================] - 0s 140us/sample - loss: 0.0751
Epoch 44/100
188/188 [==============================] - 0s 124us/sample - loss: 0.0731
Epoch 45/100
188/188 [==============================] - 0s 128us/sample - loss: 0.0692
Epoch 46/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0679
Epoch 47/100
188/188 [==============================] - 0s 132us/sample - loss: 0.0663
Epoch 48/100
188/188 [==============================] - 0s 147us/sample - loss: 0.0619
Epoch 49/100
188/188 [==============================] - 0s 117us/sample - loss: 0.0599
Epoch 50/100
188/188 [==============================] - 0s 146us/sample - loss: 0.0558
Epoch 51/100
188/188 [==============================] - 0s 126us/sample - loss: 0.0542
Epoch 52/100
188/188 [==============================] - 0s 129us/sample - loss: 0.0540
Epoch 53/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0487
Epoch 54/100
188/188 [==============================] - 0s 120us/sample - loss: 0.0471
Epoch 55/100
188/188 [==============================] - 0s 117us/sample - loss: 0.0462
Epoch 56/100
188/188 [==============================] - 0s 106us/sample - loss: 0.0425
Epoch 57/100
188/188 [==============================] - 0s 102us/sample - loss: 0.0442
Epoch 58/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0397
Epoch 59/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0361
Epoch 60/100
188/188 [==============================] - 0s 106us/sample - loss: 0.0349
Epoch 61/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0341
Epoch 62/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0322
Epoch 63/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0295
Epoch 64/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0282
Epoch 65/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0265
Epoch 66/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0250
Epoch 67/100
188/188 [==============================] - 0s 117us/sample - loss: 0.0236
Epoch 68/100
188/188 [==============================] - 0s 121us/sample - loss: 0.0218
Epoch 69/100
188/188 [==============================] - 0s 109us/sample - loss: 0.0208
Epoch 70/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0201
Epoch 71/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0200
Epoch 72/100
188/188 [==============================] - 0s 116us/sample - loss: 0.0190
Epoch 73/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0163
Epoch 74/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0159
Epoch 75/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0146
Epoch 76/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0132
Epoch 77/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0124
Epoch 78/100
188/188 [==============================] - 0s 156us/sample - loss: 0.0116
Epoch 79/100
188/188 [==============================] - 0s 158us/sample - loss: 0.0111
Epoch 80/100
188/188 [==============================] - 0s 163us/sample - loss: 0.0108
Epoch 81/100
188/188 [==============================] - 0s 174us/sample - loss: 0.0099
Epoch 82/100
188/188 [==============================] - 0s 138us/sample - loss: 0.0094
Epoch 83/100
188/188 [==============================] - 0s 148us/sample - loss: 0.0088
Epoch 84/100
188/188 [==============================] - 0s 134us/sample - loss: 0.0096
Epoch 85/100
188/188 [==============================] - 0s 128us/sample - loss: 0.0086
Epoch 86/100
188/188 [==============================] - 0s 124us/sample - loss: 0.0079
Epoch 87/100
188/188 [==============================] - 0s 151us/sample - loss: 0.0075
Epoch 88/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0069
Epoch 89/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0072
Epoch 90/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0065
Epoch 91/100
188/188 [==============================] - 0s 134us/sample - loss: 0.0059
Epoch 92/100
188/188 [==============================] - 0s 145us/sample - loss: 0.0053
Epoch 93/100
188/188 [==============================] - 0s 101us/sample - loss: 0.0054
Epoch 94/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0054
Epoch 95/100

188/188 [==============================] - 0s 120us/sample - loss: 0.0053
Epoch 96/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0050
Epoch 97/100
188/188 [==============================] - 0s 92us/sample - loss: 0.0048
Epoch 98/100
188/188 [==============================] - 0s 108us/sample - loss: 0.0057
Epoch 99/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0051
Epoch 100/100
188/188 [==============================] - 0s 108us/sample - loss: 0.0053

In [150]:
# Evaluate the model using the test data - mean
model_loss = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}")

63/1 - 0s - loss: 0.0495
Loss: 0.05936840501806093

In [151]:
#y_pred.shape
y_pred_all.shape

(251, 1)

In [152]:
#y_pred
y_pred_all

array([[ 14.70200917],
       [ 10.84844751],
       [ 13.07456127],
       [ 12.84679522],
       [  6.35680811],
       [  5.41419789],
       [ 16.0734251 ],
       [  2.6417813 ],
       [ 60.22255511],
       [  2.65067815],
       [ 19.39039493],
       [ 15.12140408],
       [ 33.13844567],
       [  7.08354239],
       [ 13.23336756],
       [ 19.74689167],
       [ 19.17831193],
       [  6.84453063],
       [  8.81924803],
       [ 19.55773108],
       [  8.160503  ],
       [ 13.48625922],
       [  9.56148731],
       [ 32.71824135],
       [ 21.73052538],
       [  5.41419789],
       [ 18.07843077],
       [ 21.01282542],
       [ 30.04372603],
       [  1.40301508],
       [ 10.36926277],
       [ 13.75071898],
       [ 18.03743637],
       [ 26.46116366],
       [ 11.11882542],
       [  5.41419789],
       [  5.41419789],
       [  7.41868278],
       [ 13.71005385],
       [ 10.00785709],
       [ 26.90401376],
       [  1.40301508],
       [  5.41419789],
       [ 19.01448778],
       [  7.62380888],
       [  7.66770322],
       [ 27.54126079],
       [  8.5477061 ],
       [ 12.39630492],
       [ 35.31862147],
       [ 36.52936869],
       [  5.41419789],
       [ 10.45783601],
       [  5.41419789],
       [  6.45923412],
       [ 20.97812343],
       [  9.1571871 ],
       [ 33.33089133],
       [  9.40049372],
       [ 11.22610236],
       [ 12.92600496],
       [  0.6465385 ],
       [  7.89173033],
       [  5.41419789],
       [ 28.07753981],
       [ 14.31252177],
       [  1.40301508],
       [  5.14600429],
       [  6.11477334],
       [ 23.8399567 ],
       [ 20.13710454],
       [  3.40860648],
       [ 20.986028  ],
       [ 10.1688291 ],
       [  8.75288689],
       [ 18.52067736],
       [ 26.66802384],
       [ 12.79799712],
       [-22.64235882],
       [  4.07713695],
       [ 18.43341335],
       [  7.89173033],
       [  6.45102024],
       [  6.24887014],
       [ -0.13063529],
       [  7.08354239],
       [ 26.61050406],
       [ 10.03170618],
       [ 35.14785262],
       [ 12.37584292],
       [ 27.97115463],
       [  3.04125394],
       [ 16.49521956],
       [ 20.50134241],
       [ 10.68899477],
       [ 51.65465675],
       [ 19.61395819],
       [  5.41419789],
       [ 21.31730066],
       [  3.40860648],
       [ 20.62956236],
       [  2.26354301],
       [  6.65296411],
       [  4.9029811 ],
       [  7.88922642],
       [ 31.25178164],
       [ 33.53438788],
       [  4.07713695],
       [ 24.8243221 ],
       [ 21.66032159],
       [  5.41419789],
       [ 22.44843104],
       [ 41.79255739],
       [ 31.96437588],
       [ 24.21960572],
       [ 19.71611363],
       [ 18.91345649],
       [ 11.25513441],
       [ 22.42208891],
       [  5.41419789],
       [  7.68978646],
       [ 11.46306122],
       [  5.41419789],
       [  3.37263537],
       [  5.41419789],
       [ 19.09032347],
       [  1.40301508],
       [ 10.49094361],
       [ 20.76327095],
       [ 13.49715587],
       [  7.27129068],
       [-22.64235882],
       [ 17.91203989],
       [ 25.6069861 ],
       [ 27.61701283],
       [ 10.94206614],
       [  8.58278899],
       [ 14.52613043],
       [  5.41419789],
       [ 10.14090103],
       [ -1.3590529 ],
       [ 17.12536952],
       [  6.24887014],
       [  1.40301508],
       [ 24.13283409],
       [  5.41419789],
       [  7.49850317],
       [ 14.56304637],
       [ 33.47221678],
       [ 16.49367207],
       [ -8.1323037 ],
       [ 33.42015097],
       [  1.40301508],
       [ 19.61730675],
       [ 22.37797067],
       [  5.41419789],
       [ 22.08171692],
       [ 10.4131594 ],
       [  5.41419789],
       [ 17.83662034],
       [ 12.98005179],
       [  5.41419789],
       [ 23.84036626],
       [ 26.60746852],
       [ 16.04302933],
       [ 16.85467962],
       [ 20.27854426],
       [ 13.40226892],
       [ 58.77356304],
       [ 12.60171344],
       [  8.31946461],
       [  3.89820373],
       [ 16.00855931],
       [ 18.97475674],
       [ 15.53542818],
       [  3.48342137],
       [ 28.82904685],
       [ 25.42012221],
       [  9.21778133],
       [ 16.37354443],
       [  4.6473727 ],
       [ 19.39416189],
       [ 13.462802  ],
       [ 18.81686624],
       [ 21.26940423],
       [ 24.57080943],
       [ 19.72362361],
       [  5.41419789],
       [  9.56148731],
       [  7.4878426 ],
       [ 27.16409838],
       [ 15.92704881],
       [ 10.35008389],
       [  6.45102024],
       [  0.44619197],
       [ 50.03907493],
       [ 41.40626007],
       [ 35.98906933],
       [  7.5768896 ],
       [ 18.64796989],
       [ 27.55075567],
       [ 35.47123992],
       [  5.41419789],
       [  4.26411068],
       [ 11.94250287],
       [ 34.20046531],
       [ 22.2394953 ],
       [  1.53801366],
       [ 15.15560372],
       [ 23.01214801],
       [ 19.54036462],
       [  7.4878426 ],
       [  2.74007602],
       [ 41.97411244],
       [  5.41419789],
       [  6.24887014],
       [ 10.68899477],
       [  5.41419789],
       [ 57.20576033],
       [ 13.26822007],
       [  8.75542965],
       [ 12.43671813],
       [ 39.06300864],
       [  5.41419789],
       [ 27.43311834],
       [ 12.99741868],
       [ 23.42873715],
       [  9.21778133],
       [  3.07235958],
       [ 30.73505953],
       [ 34.80290015],
       [ 18.22406861],
       [ 23.43291539],
       [ 11.39817623],
       [  5.74648145],
       [  5.41419789],
       [ 22.67801906],
       [ 16.5934294 ],
       [ 11.44925146],
       [ 24.22491741],
       [ 17.60272368],
       [ 23.76634365],
       [ 14.65430418],
       [ 24.32880467],
       [ 25.28439558],
       [  7.89173033],
       [  7.12826379],
       [  8.88656266],
       [ 10.09464627],
       [  8.75288689],
       [  5.41419789]])

In [153]:
#np.rint(y_pred)
y_pred_all_clean = np.rint(y_pred_all)
y_pred_all_clean

array([[ 15.],
       [ 11.],
       [ 13.],
       [ 13.],
       [  6.],
       [  5.],
       [ 16.],
       [  3.],
       [ 60.],
       [  3.],
       [ 19.],
       [ 15.],
       [ 33.],
       [  7.],
       [ 13.],
       [ 20.],
       [ 19.],
       [  7.],
       [  9.],
       [ 20.],
       [  8.],
       [ 13.],
       [ 10.],
       [ 33.],
       [ 22.],
       [  5.],
       [ 18.],
       [ 21.],
       [ 30.],
       [  1.],
       [ 10.],
       [ 14.],
       [ 18.],
       [ 26.],
       [ 11.],
       [  5.],
       [  5.],
       [  7.],
       [ 14.],
       [ 10.],
       [ 27.],
       [  1.],
       [  5.],
       [ 19.],
       [  8.],
       [  8.],
       [ 28.],
       [  9.],
       [ 12.],
       [ 35.],
       [ 37.],
       [  5.],
       [ 10.],
       [  5.],
       [  6.],
       [ 21.],
       [  9.],
       [ 33.],
       [  9.],
       [ 11.],
       [ 13.],
       [  1.],
       [  8.],
       [  5.],
       [ 28.],
       [ 14.],
       [  1.],
       [  5.],
       [  6.],
       [ 24.],
       [ 20.],
       [  3.],
       [ 21.],
       [ 10.],
       [  9.],
       [ 19.],
       [ 27.],
       [ 13.],
       [-23.],
       [  4.],
       [ 18.],
       [  8.],
       [  6.],
       [  6.],
       [ -0.],
       [  7.],
       [ 27.],
       [ 10.],
       [ 35.],
       [ 12.],
       [ 28.],
       [  3.],
       [ 16.],
       [ 21.],
       [ 11.],
       [ 52.],
       [ 20.],
       [  5.],
       [ 21.],
       [  3.],
       [ 21.],
       [  2.],
       [  7.],
       [  5.],
       [  8.],
       [ 31.],
       [ 34.],
       [  4.],
       [ 25.],
       [ 22.],
       [  5.],
       [ 22.],
       [ 42.],
       [ 32.],
       [ 24.],
       [ 20.],
       [ 19.],
       [ 11.],
       [ 22.],
       [  5.],
       [  8.],
       [ 11.],
       [  5.],
       [  3.],
       [  5.],
       [ 19.],
       [  1.],
       [ 10.],
       [ 21.],
       [ 13.],
       [  7.],
       [-23.],
       [ 18.],
       [ 26.],
       [ 28.],
       [ 11.],
       [  9.],
       [ 15.],
       [  5.],
       [ 10.],
       [ -1.],
       [ 17.],
       [  6.],
       [  1.],
       [ 24.],
       [  5.],
       [  7.],
       [ 15.],
       [ 33.],
       [ 16.],
       [ -8.],
       [ 33.],
       [  1.],
       [ 20.],
       [ 22.],
       [  5.],
       [ 22.],
       [ 10.],
       [  5.],
       [ 18.],
       [ 13.],
       [  5.],
       [ 24.],
       [ 27.],
       [ 16.],
       [ 17.],
       [ 20.],
       [ 13.],
       [ 59.],
       [ 13.],
       [  8.],
       [  4.],
       [ 16.],
       [ 19.],
       [ 16.],
       [  3.],
       [ 29.],
       [ 25.],
       [  9.],
       [ 16.],
       [  5.],
       [ 19.],
       [ 13.],
       [ 19.],
       [ 21.],
       [ 25.],
       [ 20.],
       [  5.],
       [ 10.],
       [  7.],
       [ 27.],
       [ 16.],
       [ 10.],
       [  6.],
       [  0.],
       [ 50.],
       [ 41.],
       [ 36.],
       [  8.],
       [ 19.],
       [ 28.],
       [ 35.],
       [  5.],
       [  4.],
       [ 12.],
       [ 34.],
       [ 22.],
       [  2.],
       [ 15.],
       [ 23.],
       [ 20.],
       [  7.],
       [  3.],
       [ 42.],
       [  5.],
       [  6.],
       [ 11.],
       [  5.],
       [ 57.],
       [ 13.],
       [  9.],
       [ 12.],
       [ 39.],
       [  5.],
       [ 27.],
       [ 13.],
       [ 23.],
       [  9.],
       [  3.],
       [ 31.],
       [ 35.],
       [ 18.],
       [ 23.],
       [ 11.],
       [  6.],
       [  5.],
       [ 23.],
       [ 17.],
       [ 11.],
       [ 24.],
       [ 18.],
       [ 24.],
       [ 15.],
       [ 24.],
       [ 25.],
       [  8.],
       [  7.],
       [  9.],
       [ 10.],
       [  9.],
       [  5.]])

In [154]:
y_pred_all_clean[y_pred_all_clean <= 0] = 0
y_pred_all_clean

array([[15.],
       [11.],
       [13.],
       [13.],
       [ 6.],
       [ 5.],
       [16.],
       [ 3.],
       [60.],
       [ 3.],
       [19.],
       [15.],
       [33.],
       [ 7.],
       [13.],
       [20.],
       [19.],
       [ 7.],
       [ 9.],
       [20.],
       [ 8.],
       [13.],
       [10.],
       [33.],
       [22.],
       [ 5.],
       [18.],
       [21.],
       [30.],
       [ 1.],
       [10.],
       [14.],
       [18.],
       [26.],
       [11.],
       [ 5.],
       [ 5.],
       [ 7.],
       [14.],
       [10.],
       [27.],
       [ 1.],
       [ 5.],
       [19.],
       [ 8.],
       [ 8.],
       [28.],
       [ 9.],
       [12.],
       [35.],
       [37.],
       [ 5.],
       [10.],
       [ 5.],
       [ 6.],
       [21.],
       [ 9.],
       [33.],
       [ 9.],
       [11.],
       [13.],
       [ 1.],
       [ 8.],
       [ 5.],
       [28.],
       [14.],
       [ 1.],
       [ 5.],
       [ 6.],
       [24.],
       [20.],
       [ 3.],
       [21.],
       [10.],
       [ 9.],
       [19.],
       [27.],
       [13.],
       [ 0.],
       [ 4.],
       [18.],
       [ 8.],
       [ 6.],
       [ 6.],
       [ 0.],
       [ 7.],
       [27.],
       [10.],
       [35.],
       [12.],
       [28.],
       [ 3.],
       [16.],
       [21.],
       [11.],
       [52.],
       [20.],
       [ 5.],
       [21.],
       [ 3.],
       [21.],
       [ 2.],
       [ 7.],
       [ 5.],
       [ 8.],
       [31.],
       [34.],
       [ 4.],
       [25.],
       [22.],
       [ 5.],
       [22.],
       [42.],
       [32.],
       [24.],
       [20.],
       [19.],
       [11.],
       [22.],
       [ 5.],
       [ 8.],
       [11.],
       [ 5.],
       [ 3.],
       [ 5.],
       [19.],
       [ 1.],
       [10.],
       [21.],
       [13.],
       [ 7.],
       [ 0.],
       [18.],
       [26.],
       [28.],
       [11.],
       [ 9.],
       [15.],
       [ 5.],
       [10.],
       [ 0.],
       [17.],
       [ 6.],
       [ 1.],
       [24.],
       [ 5.],
       [ 7.],
       [15.],
       [33.],
       [16.],
       [ 0.],
       [33.],
       [ 1.],
       [20.],
       [22.],
       [ 5.],
       [22.],
       [10.],
       [ 5.],
       [18.],
       [13.],
       [ 5.],
       [24.],
       [27.],
       [16.],
       [17.],
       [20.],
       [13.],
       [59.],
       [13.],
       [ 8.],
       [ 4.],
       [16.],
       [19.],
       [16.],
       [ 3.],
       [29.],
       [25.],
       [ 9.],
       [16.],
       [ 5.],
       [19.],
       [13.],
       [19.],
       [21.],
       [25.],
       [20.],
       [ 5.],
       [10.],
       [ 7.],
       [27.],
       [16.],
       [10.],
       [ 6.],
       [ 0.],
       [50.],
       [41.],
       [36.],
       [ 8.],
       [19.],
       [28.],
       [35.],
       [ 5.],
       [ 4.],
       [12.],
       [34.],
       [22.],
       [ 2.],
       [15.],
       [23.],
       [20.],
       [ 7.],
       [ 3.],
       [42.],
       [ 5.],
       [ 6.],
       [11.],
       [ 5.],
       [57.],
       [13.],
       [ 9.],
       [12.],
       [39.],
       [ 5.],
       [27.],
       [13.],
       [23.],
       [ 9.],
       [ 3.],
       [31.],
       [35.],
       [18.],
       [23.],
       [11.],
       [ 6.],
       [ 5.],
       [23.],
       [17.],
       [11.],
       [24.],
       [18.],
       [24.],
       [15.],
       [24.],
       [25.],
       [ 8.],
       [ 7.],
       [ 9.],
       [10.],
       [ 9.],
       [ 5.]])

In [155]:
forward_players['Pred_TlkW'] = y_pred_all_clean
forward_players

                Pred_TlkW
Player
Aaron Connolly       15.0
Aaron Lennon         11.0
Aaron Mooy           13.0
Adam Idah            13.0
Adam Lallana          6.0
...                   ...
Yoshinori Mut≈ç        7.0
Yves Bissouma         9.0
√ârik Lamela          10.0
√âtienne Capoue        9.0
ƒ∞lkay G√ºndoƒüan        5.0

[251 rows x 1 columns]

In [156]:
pred_TlkW_df = forward_players
pred_TlkW_df

                Pred_TlkW
Player
Aaron Connolly       15.0
Aaron Lennon         11.0
Aaron Mooy           13.0
Adam Idah            13.0
Adam Lallana          6.0
...                   ...
Yoshinori Mut≈ç        7.0
Yves Bissouma         9.0
√ârik Lamela          10.0
√âtienne Capoue        9.0
ƒ∞lkay G√ºndoƒüan        5.0

[251 rows x 1 columns]

In [158]:
pred_TlkW_df.to_csv('pred_TlkW.csv')

In [159]:
y_pred_nn = nn.predict(X_test_scaled)#X_scaler.transform(X))
y_pred_nn
pd.DataFrame({'y_pred_nn': y_pred_nn[:,0], 'y_test': y_test[:,0]})

    y_pred_nn    y_test
0   -0.093745  0.000000
1    0.349972  0.000000
2    0.324555  0.480000
3    0.553639  0.428571
4    0.596556  0.476190
..        ...       ...
58   0.691537  0.687500
59   0.967240  1.000000
60   0.283950  0.370370
61   1.329672  1.043478
62   0.153059  0.166667

[63 rows x 2 columns]