In [1]:
import requests
from splinter import Browser
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
!which chromedriver

/usr/local/bin/chromedriver

In [3]:
executable_path= {'executable_path': "/usr/local/bin/chromedriver"}
browser = Browser('chrome', **executable_path)

In [4]:
# URL is for a single match (gives player stats for that match)
url = 'https://fbref.com/en/matches/3aee1ba7/Liverpool-West-Ham-United-February-24-2020-Premier-League'
browser.visit(url)
# home team = Liverpool, away team = West Ham

In [5]:
# Parse the HTML
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [6]:
df = pd.read_html(url)
df

[   Liverpool (4-3-3)      Liverpool (4-3-3).1
 0                  1                  Alisson
 1                  3                  Fabinho
 2                  4          Virgil van Dijk
 3                  5      Georginio Wijnaldum
 4                  8               Naby Keïta
 5                  9          Roberto Firmino
 6                 10               Sadio Mané
 7                 11            Mohamed Salah
 8                 12                Joe Gomez
 9                 26         Andrew Robertson
 10                66   Trent Alexander-Arnold
 11             Bench                    Bench
 12                13                   Adrián
 13                 6             Dejan Lovren
 14                15  Alex Oxlade-Chamberlain
 15                18          Takumi Minamino
 16                20             Adam Lallana
 17                27             Divock Origi
 18                32               Joël Matip,
    West Ham (4-2-3-1) West Ham (4-2-3-1).1
 0                   1     Łukasz Fabiański
 1                   3      Aaron Cresswell
 2                   8      Felipe Anderson
 3                  11     Robert Snodgrass
 4                  16           Mark Noble
 5                  21       Angelo Ogbonna
 6                  23            Issa Diop
 7                  28         Tomáš Souček
 8                  30      Michail Antonio
 9                  41          Declan Rice
 10                 52        Jeremy Ngakia
 11              Bench                Bench
 12                 35      Darren Randolph
 13                  4      Fabián Balbuena
 14                  5       Pablo Zabaleta
 15                 10       Manuel Lanzini
 16                 17         Jarrod Bowen
 17                 18        Pablo Fornals
 18                 22     Sébastien Haller,
           Liverpool          West Ham
          Possession        Possession
 0               70%               30%
 1  Passing Accuracy  Passing Accuracy
 2  525 of 622 — 84%  66% — 175 of 265
 3   Shots on Target   Shots on Target
 4     7 of 25 — 28%      57% — 4 of 7
 5             Saves             Saves
 6      2 of 4 — 50%      57% — 4 of 7
 7             Cards             Cards
 8               NaN               NaN,
                      Player   #   Nation Pos   Min  Gls  Ast   xG  npxG   xA  \
 0           Roberto Firmino   9   br BRA  FW  90.0    0    0  1.0   1.0  0.1
 1                Sadio Mané  10   sn SEN  LW  90.0    1    0  0.8   0.8  0.0
 2                Joël Matip  32   cm CMR  CB   NaN    0    0  0.0   0.0  0.0
 3             Mohamed Salah  11   eg EGY  RW  90.0    1    0  0.4   0.4  0.1
 4       Georginio Wijnaldum   5   nl NED  CM  90.0    1    0  0.2   0.2  0.0
 5                Naby Keïta   8   gn GUI  CM  57.0    0    0  0.0   0.0  0.0
 6   Alex Oxlade-Chamberlain  15  eng ENG  CM  33.0    0    0  0.0   0.0  0.0
 7                   Fabinho   3   br BRA  DM  90.0    0    0  0.1   0.1  0.1
 8          Andrew Robertson  26  sco SCO  LB  90.0    0    1  0.1   0.1  0.5
 9           Virgil van Dijk   4   nl NED  CB  90.0    0    0  0.2   0.2  0.0
 10                Joe Gomez  12  eng ENG  CB  90.0    0    0  0.0   0.0  0.0
 11   Trent Alexander-Arnold  66  eng ENG  RB  90.0    0    2  0.2   0.2  0.6
 12                  Alisson   1   br BRA  GK  90.0    0    0  0.0   0.0  0.0

     Sh  SoT  Fls  Fld  Crs  TklW  Int  CrdY  CrdR
 0    5    0    1    0    1     1    1     0     0
 1    3    1    0    3    2     2    0     0     0
 2    0    0    1    0    0     0    0     0     0
 3    5    3    1    0    0     0    0     0     0
 4    1    1    0    1    1     1    0     0     0
 5    0    0    0    2    0     2    0     0     0
 6    1    0    0    1    3     0    1     0     0
 7    1    0    1    1    2     3    1     0     0
 8    1    0    0    0   11     4    1     0     0
 9    3    1    0    0    0     0    0     0     0
 10   1    0    0    0    0     1    0     0     0
 11   4    1    0    1   19     2    0     0     0
 12   0    0    0    0    0     0    0     0     0  ,
     Player  Nation  Min  GA  Saves  Save%
 0  Alisson  br BRA   90   2      2   50.0,
               Player   #   Nation    Pos  Min  Gls  Ast   xG  npxG   xA  Sh  \
 0    Michail Antonio  30  eng ENG  FW,LW   90    0    0  0.0   0.0  0.2   0
 1    Felipe Anderson   8   br BRA     LW   65    0    0  0.0   0.0  0.0   1
 2   Sébastien Haller  22   fr FRA     FW   25    0    0  0.0   0.0  0.0   1
 3   Robert Snodgrass  11  sco SCO     RW   84    0    1  0.0   0.0  0.1   0
 4       Jarrod Bowen  17  eng ENG     RW    6    0    0  0.2   0.2  0.0   1
 5         Mark Noble  16  eng ENG  AM,DM   90    0    0  0.1   0.1  0.0   1
 6       Tomáš Souček  28   cz CZE     DM   47    0    0  0.0   0.0  0.0   0
 7      Pablo Fornals  18   es ESP     AM   43    1    0  0.1   0.1  0.0   1
 8        Declan Rice  41  eng ENG     DM   90    0    1  0.0   0.0  0.1   0
 9    Aaron Cresswell   3  eng ENG     LB   90    0    0  0.1   0.1  0.0   1
 10    Angelo Ogbonna  21   it ITA     CB   90    0    0  0.0   0.0  0.0   0
 11         Issa Diop  23   fr FRA     CB   90    1    0  0.1   0.1  0.0   1
 12     Jeremy Ngakia  52  eng ENG     RB   90    0    0  0.0   0.0  0.0   0
 13  Łukasz Fabiański   1   pl POL     GK   90    0    0  0.0   0.0  0.0   0

     SoT  Fls  Fld  Crs  TklW  Int  CrdY  CrdR
 0     0    1    1    7     1    0     0     0
 1     0    1    0    2     3    0     0     0
 2     1    0    0    0     0    0     0     0
 3     0    0    0    6     2    0     0     0
 4     1    0    0    0     0    0     0     0
 5     0    2    1    0     1    1     1     0
 6     0    1    0    0     1    2     0     0
 7     1    1    1    1     0    0     0     0
 8     0    1    0    2     2    1     1     0
 9     0    0    0    4     0    2     0     0
 10    0    0    1    0     2    3     0     0
 11    1    1    0    0     1    1     1     0
 12    0    2    0    3     4    3     0     0
 13    0    0    0    0     0    0     0     0  ,
              Player  Nation  Min  GA  Saves  Save%
 0  Łukasz Fabiański  pl POL   90   3      4   57.1]

In [7]:
# Home team match stats
home_df = df[3]
home_df

,Player,#,Nation,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,CrdR
0,Roberto Firmino,9,br BRA,FW,90.0,0,0,1.0,1.0,0.1,5,0,1,0,1,1,1,0,0
1,Sadio Mané,10,sn SEN,LW,90.0,1,0,0.8,0.8,0.0,3,1,0,3,2,2,0,0,0
2,Joël Matip,32,cm CMR,CB,NaN,0,0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0
3,Mohamed Salah,11,eg EGY,RW,90.0,1,0,0.4,0.4,0.1,5,3,1,0,0,0,0,0,0
4,Georginio Wijnaldum,5,nl NED,CM,90.0,1,0,0.2,0.2,0.0,1,1,0,1,1,1,0,0,0
5,Naby Keïta,8,gn GUI,CM,57.0,0,0,0.0,0.0,0.0,0,0,0,2,0,2,0,0,0
6,Alex Oxlade-Chamberlain,15,eng ENG,CM,33.0,0,0,0.0,0.0,0.0,1,0,0,1,3,0,1,0,0
7,Fabinho,3,br BRA,DM,90.0,0,0,0.1,0.1,0.1,1,0,1,1,2,3,1,0,0
8,Andrew Robertson,26,sco SCO,LB,90.0,0,1,0.1,0.1,0.5,1,0,0,0,11,4,1,0,0
9,Virgil van Dijk,4,nl NED,CB,90.0,0,0,0.2,0.2,0.0,3,1,0,0,0,0,0,0,0
10,Joe Gomez,12,eng ENG,CB,90.0,0,0,0.0,0.0,0.0,1,0,0,0,0,1,0,0,0
11,Trent Alexander-Arnold,66,eng ENG,RB,90.0,0,2,0.2,0.2,0.6,4,1,0,1,19,2,0,0,0
12,Alisson,1,br BRA,GK,90.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [8]:
# Home goalie match stats
home_g_df = df[4]
home_g_df

    Player  Nation  Min  GA  Saves  Save%
0  Alisson  br BRA   90   2      2   50.0

In [9]:
# Away team match stats
away_df = df[5]
away_df

,Player,#,Nation,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,CrdR
0,Michail Antonio,30,eng ENG,"FW,LW",90,0,0,0.0,0.0,0.2,0,0,1,1,7,1,0,0,0
1,Felipe Anderson,8,br BRA,LW,65,0,0,0.0,0.0,0.0,1,0,1,0,2,3,0,0,0
2,Sébastien Haller,22,fr FRA,FW,25,0,0,0.0,0.0,0.0,1,1,0,0,0,0,0,0,0
3,Robert Snodgrass,11,sco SCO,RW,84,0,1,0.0,0.0,0.1,0,0,0,0,6,2,0,0,0
4,Jarrod Bowen,17,eng ENG,RW,6,0,0,0.2,0.2,0.0,1,1,0,0,0,0,0,0,0
5,Mark Noble,16,eng ENG,"AM,DM",90,0,0,0.1,0.1,0.0,1,0,2,1,0,1,1,1,0
6,Tomáš Souček,28,cz CZE,DM,47,0,0,0.0,0.0,0.0,0,0,1,0,0,1,2,0,0
7,Pablo Fornals,18,es ESP,AM,43,1,0,0.1,0.1,0.0,1,1,1,1,1,0,0,0,0
8,Declan Rice,41,eng ENG,DM,90,0,1,0.0,0.0,0.1,0,0,1,0,2,2,1,1,0
9,Aaron Cresswell,3,eng ENG,LB,90,0,0,0.1,0.1,0.0,1,0,0,0,4,0,2,0,0
10,Angelo Ogbonna,21,it ITA,CB,90,0,0,0.0,0.0,0.0,0,0,0,1,0,2,3,0,0
11,Issa Diop,23,fr FRA,CB,90,1,0,0.1,0.1,0.0,1,1,1,0,0,1,1,1,0
12,Jeremy Ngakia,52,eng ENG,RB,90,0,0,0.0,0.0,0.0,0,0,2,0,3,4,3,0,0
13,Łukasz Fabiański,1,pl POL,GK,90,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [10]:
# Away goalie match stats
away_g_df = df[6]
away_g_df

             Player  Nation  Min  GA  Saves  Save%
0  Łukasz Fabiański  pl POL   90   3      4   57.1