In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine('postgres://tklyplugonrpes:1d19818b40604e8d36f7dd7f66de9713540fd45412c8cec9661c5f2d694da75c@ec2-54-80-184-43.compute-1.amazonaws.com:5432/d43qmrqacsbjj0')

In [4]:
api_fwd_data_df = pd.read_csv('forward_epl_players_ready_df.csv')
api_fwd_data_df

,index,player_id,first_name,last_name,position,team_id,club,calendar,number_of_matches,total_appearances,...,total_tackle,touches,was_fouled,won_contest,yellow_card,penalty_save,penalty_faced,saves,dive_save,stand_save
0,0,54694,Pierre-Emerick,Aubameyang,4,3,Arsenal,2017,38,13,...,1,25,0,0,0,0,0,0,0,0
1,1,54694,Pierre-Emerick,Aubameyang,4,3,Arsenal,2017,38,13,...,0,23,0,0,0,0,0,0,0,0
2,2,54694,Pierre-Emerick,Aubameyang,4,3,Arsenal,2017,38,13,...,0,27,0,2,0,0,0,0,0,0
3,3,54694,Pierre-Emerick,Aubameyang,4,3,Arsenal,2017,38,13,...,1,29,1,1,0,0,0,0,0,0
4,4,54694,Pierre-Emerick,Aubameyang,4,3,Arsenal,2017,38,13,...,0,24,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3114,3114,102057,Raúl,Jiménez,4,39,Wolverhampton,2019,29,29,...,1,41,2,4,0,0,0,0,0,0
3115,3115,102057,Raúl,Jiménez,4,39,Wolverhampton,2019,29,29,...,1,50,2,4,0,0,0,0,0,0
3116,3116,102057,Raúl,Jiménez,4,39,Wolverhampton,2019,29,29,...,0,42,0,1,1,0,0,0,0,0
3117,3117,102057,Raúl,Jiménez,4,39,Wolverhampton,2019,29,29,...,1,48,0,3,0,0,0,0,0,0
3118,3118,102057,Raúl,Jiménez,4,39,Wolverhampton,2019,29,29,...,0,52,2,0,0,0,0,0,0,0

In [5]:
api_fwd_data_df.to_sql('api_fwd_data', con=engine)