In [1]:
import pandas as pd

In [4]:
players_2020_df = pd.read_csv('current_prem_players.csv')

In [5]:
players_2020_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Playing Time,Playing Time.1,Playing Time.2,...,Expected,Expected.1,Expected.2,Per 90 Minutes.5,Per 90 Minutes.6,Per 90 Minutes.7,Per 90 Minutes.8,Per 90 Minutes.9,Unnamed: 29,Unnamed: 30
0,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,xG,npxG,xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,NaN
1,1,Patrick van Aanholt,Patrick-van-Aanholt,nl NED,DF,Crystal Palace,28,1990,22,22,...,0.1,1.8,1,1.8,0.09,0.09,0.17,0.05,0.14,Matches
2,2,Max Aarons,Max-Aarons,eng ENG,DF,Norwich City,19,2000,27,27,...,0.04,0.5,0.5,3.5,0.02,0.13,0.15,0.02,0.15,Matches
3,3,Tammy Abraham,Tammy-Abraham,eng ENG,FW,Chelsea,21,1997,25,23,...,0.74,11.8,11.8,2.2,0.55,0.1,0.65,0.55,0.65,Matches
4,4,Che Adams,Che-Adams,eng ENG,FW,Southampton,23,1996,22,8,...,0.25,1.9,1.9,0.9,0.23,0.11,0.35,0.23,0.35,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,488,Pablo Zabaleta,Pablo-Zabaleta,ar ARG,DF,West Ham,34,1985,10,6,...,0,0.1,0.1,0.4,0.01,0.06,0.06,0.01,0.06,Matches
489,489,Wilfried Zaha,Wilfried-Zaha,ci CIV,MFFW,Crystal Palace,26,1992,29,28,...,0.21,4,4,2.4,0.14,0.08,0.23,0.14,0.23,Matches
490,490,Christoph Zimmermann,Christoph-Zimmermann,de GER,DF,Norwich City,26,1993,15,15,...,0.07,0.4,0.4,0,0.03,0,0.03,0.03,0.03,Matches
491,491,Oleksandr Zinchenko,Oleksandr-Zinchenko,ua UKR,DF,Manchester City,22,1996,12,10,...,0,0.3,0.3,0.7,0.03,0.07,0.11,0.03,0.11,Matches
492,492,Kurt Zouma,Kurt-Zouma,fr FRA,DF,Chelsea,24,1994,22,19,...,0,0.6,0.6,0,0.03,0,0.03,0.03,0.03,Matches

In [7]:
player_names = list(players_2020_df['Unnamed: 1'])

In [9]:
player_names = player_names[1:]