In [78]:
import pandas as pd
import numpy as np
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from tensorflow import keras
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [79]:
player_data = pd.read_csv('/Users/hunter/Desktop/Data_Class/final_project/Data/cleaned_players.csv')

In [80]:
player_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
1,James Milner,CM,4.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Midfield,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20370,Riyad Mahrez,CM,90.0,1,2,0.1,0.1,0.5,2,2,...,1,4,1,1,0,0,2018,25.0,Midfield,PL
20371,Christian Fuchs,LB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,1,0,4,0,0,2018,2.0,Defender,PL
20372,Harry Maguire,CB,90.0,0,0,0.4,0.4,0.0,4,1,...,1,0,2,5,0,0,2018,8.0,Defender,PL
20373,Wes Morgan,CB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,3,0,0,2018,2.5,Defender,PL
20374,Hamza Choudhury,RB,34.0,0,0,0.0,0.0,0.0,1,0,...,1,0,0,4,1,0,2018,-0.5,Defender,PL

In [81]:
forward_data = player_data[player_data['Position Group'] == 'Forward']
forward_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
12,Teemu Pukki,FW,83.0,1,0,0.4,0.4,0.1,3,1,...,1,0,1,1,0,0,2019,15.0,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20353,Harry Kane,FW,90.0,2,0,0.2,0.2,0.0,3,2,...,0,0,0,0,0,0,2018,24.5,Forward,PL
20354,Lucas Moura,LW,74.0,0,1,0.1,0.1,0.0,2,0,...,2,0,0,0,0,0,2018,5.0,Forward,PL
20356,√ârik Lamela,RW,78.0,2,0,1.3,1.3,0.0,2,2,...,2,1,1,2,0,0,2018,26.5,Forward,PL
20361,Son Heung-min,FW,6.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2018,1.0,Forward,PL
20366,Jamie Vardy,FW,90.0,2,0,0.5,0.5,0.3,6,2,...,0,0,0,0,0,0,2018,25.0,Forward,PL

In [82]:
# Groupby player (forward) mean
forward_data_mean = forward_data.groupby(["Player"]).mean()
forward_data_mean.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [83]:
forward_players = forward_data_mean.filter(['Player'], axis=1)
forward_players

Empty DataFrame
Columns: []
Index: [Aaron Connolly, Aaron Lennon, Aaron Mooy, Adam Idah, Adam Lallana, Adam Smith, Adama Traor√©, Ahmed Elmohamady, Ainsley Maitland-Niles, Albian Ajeti, Alex Iwobi, Alex Oxlade-Chamberlain, Alexandre Lacazette, Alexis Mac Allister, Alireza Jahanbakhsh, Allan Saint-Maximin, Andre Gray, Andreas Pereira, Andriy Yarmolenko, Andros Townsend, Andy Carroll, Angel Gomes, Anthony Gordon, Anthony Martial, Anwar El Ghazi, Armando Broja, Arthur Masuaku, Ashley Barnes, Ayoze P√©rez, Ben Chilwell, Ben Osborn, Bernard, Bernardo, Bernardo Silva, Billy Sharp, Borja Bast√≥n, Brandon Williams, Bukayo Saka, Callum Hudson-Odoi, Callum Robinson, Callum Wilson, Calum Chambers, Carlos S√°nchez, Cenk Tosun, Che Adams, Cheikhou Kouyat√©, Chris Wood, Christian Atsu, Christian Benteke, Christian Eriksen, Christian Pulisic, Ciaran Clark, Connor Wickham, Conor Hourihane, Dan Gosling, Daniel James, Daniel Podence, Danny Ings, Danny Rose, Danny Welbeck, David McGoldrick, DeAndre Yedlin, Declan Rice, Dejan Lovren, Dele Alli, Demarai Gray, Dennis Srbeny, Diego Rico, Diogo Dalot, Diogo Jota, Divock Origi, Domingos Quina, Dominic Calvert-Lewin, Dominic Solanke, Douglas Luiz, Dwight Gayle, Dwight McNeil, Eddie Nketiah, Ederson, Emerson Palmieri, Emi Buend√≠a, Emil Krafth, Eric Dier, Ezequiel Schelotto, Fabinho, Faustino Anjorin, Felipe Anderson, Florin Andone, Gabriel Jesus, Georges-K√©vin N'Koudou, Gerard Deulofeu, Giovani Lo Celso, Glenn Murray, Gylfi Sigur√∞sson, Hamza Choudhury, Harry Kane, Harry Wilson, Harry Winks, Harvey Barnes, Henri Lansbury, ...]

[251 rows x 0 columns]

In [84]:
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_var, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

In [85]:
# Create target
y_var = forward_data_mean.Fls
y_var.head()

Player
Aaron Connolly    0.687500
Aaron Lennon      0.722222
Aaron Mooy        0.384615
Adam Idah         0.000000
Adam Lallana      0.307692
Name: Fls, dtype: float64

In [86]:
player_x = forward_data_mean.drop("Fls", axis =1)
player_x.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [87]:
# Create features 
X = player_x
X.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [88]:
X_opt = X.iloc[:,:].values
X_opt

array([[4.93125000e+01, 1.25000000e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [7.36111111e+01, 5.55555556e-02, 5.55555556e-02, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [7.38461538e+01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [4.26969697e+01, 6.06060606e-02, 3.03030303e-02, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [9.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [89]:
y_var = y_var.reset_index().iloc[:,1:].values

In [90]:
# Test if features are siginiicant 
trimmed_X = backwardElimination(X_opt, 0.05)
trimmed_X

array([[1.25000000e-01, 0.00000000e+00, 1.43750000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [5.55555556e-02, 5.55555556e-02, 3.88888889e-01, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [0.00000000e+00, 0.00000000e+00, 1.38461538e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [6.06060606e-02, 3.03030303e-02, 1.09090909e+00, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [91]:
# Split our preprocessed data into our features and target arrays
y = y_var
X = trimmed_X

In [92]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [93]:
# Create scaler instance
scaler = StandardScaler()

In [94]:
# Fit the scaler
X_scaler = scaler.fit(X_train)

In [95]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [96]:
# Define the linear regression model
lin_reg = LinearRegression()

In [97]:
# Train the model
lin_reg.fit(X_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [98]:
lin_reg.score(X_train, y_train)

-444.29893124269455

In [99]:
lin_reg.score(X_test, y_test)

-348.08553836351814

In [100]:
y_pred = lin_reg.predict(X_test)

In [101]:
y_pred_all = lin_reg.predict(X)

In [102]:
r2_score(y_test, y_pred)

-348.08553836351814

In [103]:
# Define hidden layers
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 50

In [104]:
nn = tf.keras.models.Sequential()

In [105]:
# Hidden layer 1
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [106]:
# Hidden layer 2
nn.add(tf.keras.layers.Dense(units=hidden_layer2, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [107]:
# Output layer
nn.add(tf.keras.layers.Dense(units=1))

In [108]:
# Compile the model
nn.compile(loss="mean_squared_error", optimizer="adam")#, metrics=["accuracy"])

In [109]:
# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 50)                600
_________________________________________________________________
dense_7 (Dense)              (None, 50)                2550
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 51
=================================================================
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________

In [110]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Train on 188 samples
Epoch 1/100
188/188 [==============================] - 1s 4ms/sample - loss: 0.5762
Epoch 2/100
188/188 [==============================] - 0s 152us/sample - loss: 0.4669
Epoch 3/100
188/188 [==============================] - 0s 194us/sample - loss: 0.3596
Epoch 4/100
188/188 [==============================] - 0s 122us/sample - loss: 0.2768
Epoch 5/100
188/188 [==============================] - 0s 149us/sample - loss: 0.2287
Epoch 6/100
188/188 [==============================] - 0s 159us/sample - loss: 0.2075
Epoch 7/100
188/188 [==============================] - 0s 139us/sample - loss: 0.1954
Epoch 8/100
188/188 [==============================] - 0s 188us/sample - loss: 0.1807
Epoch 9/100
188/188 [==============================] - 0s 145us/sample - loss: 0.1688
Epoch 10/100
188/188 [==============================] - 0s 136us/sample - loss: 0.1596
Epoch 11/100
188/188 [==============================] - 0s 136us/sample - loss: 0.1534
Epoch 12/100
188/188 [==============================] - 0s 113us/sample - loss: 0.1483
Epoch 13/100
188/188 [==============================] - 0s 129us/sample - loss: 0.1431
Epoch 14/100
188/188 [==============================] - 0s 142us/sample - loss: 0.1397
Epoch 15/100
188/188 [==============================] - 0s 130us/sample - loss: 0.1359
Epoch 16/100
188/188 [==============================] - 0s 120us/sample - loss: 0.1331
Epoch 17/100
188/188 [==============================] - 0s 116us/sample - loss: 0.1294
Epoch 18/100
188/188 [==============================] - 0s 105us/sample - loss: 0.1266
Epoch 19/100
188/188 [==============================] - 0s 148us/sample - loss: 0.1230
Epoch 20/100
188/188 [==============================] - 0s 121us/sample - loss: 0.1206
Epoch 21/100
188/188 [==============================] - 0s 126us/sample - loss: 0.1164
Epoch 22/100
188/188 [==============================] - 0s 177us/sample - loss: 0.1134
Epoch 23/100
188/188 [==============================] - 0s 147us/sample - loss: 0.1110
Epoch 24/100
188/188 [==============================] - 0s 115us/sample - loss: 0.1070
Epoch 25/100
188/188 [==============================] - 0s 129us/sample - loss: 0.1033
Epoch 26/100
188/188 [==============================] - 0s 133us/sample - loss: 0.0995
Epoch 27/100
188/188 [==============================] - 0s 126us/sample - loss: 0.0959
Epoch 28/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0924
Epoch 29/100
188/188 [==============================] - 0s 156us/sample - loss: 0.0886
Epoch 30/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0842
Epoch 31/100
188/188 [==============================] - 0s 156us/sample - loss: 0.0797
Epoch 32/100
188/188 [==============================] - 0s 135us/sample - loss: 0.0762
Epoch 33/100
188/188 [==============================] - 0s 133us/sample - loss: 0.0721
Epoch 34/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0675
Epoch 35/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0637
Epoch 36/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0601
Epoch 37/100
188/188 [==============================] - 0s 181us/sample - loss: 0.0560
Epoch 38/100
188/188 [==============================] - 0s 149us/sample - loss: 0.0528
Epoch 39/100
188/188 [==============================] - 0s 138us/sample - loss: 0.0488
Epoch 40/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0454
Epoch 41/100
188/188 [==============================] - 0s 171us/sample - loss: 0.0435
Epoch 42/100
188/188 [==============================] - 0s 134us/sample - loss: 0.0391
Epoch 43/100
188/188 [==============================] - 0s 122us/sample - loss: 0.0360
Epoch 44/100
188/188 [==============================] - 0s 116us/sample - loss: 0.0325
Epoch 45/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0292
Epoch 46/100
188/188 [==============================] - 0s 129us/sample - loss: 0.0266
Epoch 47/100
188/188 [==============================] - 0s 108us/sample - loss: 0.0240
Epoch 48/100
188/188 [==============================] - 0s 143us/sample - loss: 0.0215
Epoch 49/100
188/188 [==============================] - 0s 147us/sample - loss: 0.0191
Epoch 50/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0172
Epoch 51/100
188/188 [==============================] - 0s 129us/sample - loss: 0.0148
Epoch 52/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0132
Epoch 53/100
188/188 [==============================] - 0s 119us/sample - loss: 0.0116
Epoch 54/100
188/188 [==============================] - 0s 105us/sample - loss: 0.0102
Epoch 55/100
188/188 [==============================] - 0s 129us/sample - loss: 0.0089
Epoch 56/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0075
Epoch 57/100
188/188 [==============================] - 0s 146us/sample - loss: 0.0065
Epoch 58/100
188/188 [==============================] - 0s 135us/sample - loss: 0.0063
Epoch 59/100
188/188 [==============================] - 0s 137us/sample - loss: 0.0062
Epoch 60/100
188/188 [==============================] - 0s 126us/sample - loss: 0.0047
Epoch 61/100
188/188 [==============================] - 0s 99us/sample - loss: 0.0045
Epoch 62/100
188/188 [==============================] - 0s 127us/sample - loss: 0.0036
Epoch 63/100
188/188 [==============================] - 0s 157us/sample - loss: 0.0048
Epoch 64/100
188/188 [==============================] - 0s 164us/sample - loss: 0.0035
Epoch 65/100
188/188 [==============================] - 0s 116us/sample - loss: 0.0028
Epoch 66/100
188/188 [==============================] - 0s 120us/sample - loss: 0.0024
Epoch 67/100
188/188 [==============================] - 0s 106us/sample - loss: 0.0023
Epoch 68/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0020
Epoch 69/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0018
Epoch 70/100
188/188 [==============================] - 0s 119us/sample - loss: 0.0017
Epoch 71/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0015
Epoch 72/100
188/188 [==============================] - 0s 108us/sample - loss: 0.0014
Epoch 73/100
188/188 [==============================] - 0s 106us/sample - loss: 0.0013
Epoch 74/100
188/188 [==============================] - 0s 145us/sample - loss: 0.0013
Epoch 75/100
188/188 [==============================] - 0s 171us/sample - loss: 0.0012
Epoch 76/100
188/188 [==============================] - 0s 104us/sample - loss: 0.0011
Epoch 77/100
188/188 [==============================] - 0s 109us/sample - loss: 0.0011
Epoch 78/100
188/188 [==============================] - 0s 121us/sample - loss: 0.0010
Epoch 79/100
188/188 [==============================] - 0s 107us/sample - loss: 9.6134e-04
Epoch 80/100
188/188 [==============================] - 0s 115us/sample - loss: 9.3200e-04
Epoch 81/100
188/188 [==============================] - 0s 123us/sample - loss: 8.9724e-04
Epoch 82/100
188/188 [==============================] - 0s 123us/sample - loss: 9.0905e-04
Epoch 83/100
188/188 [==============================] - 0s 137us/sample - loss: 8.7699e-04
Epoch 84/100
188/188 [==============================] - 0s 115us/sample - loss: 8.1167e-04
Epoch 85/100
188/188 [==============================] - 0s 124us/sample - loss: 7.9998e-04
Epoch 86/100
188/188 [==============================] - 0s 122us/sample - loss: 7.9990e-04
Epoch 87/100
188/188 [==============================] - 0s 132us/sample - loss: 7.4197e-04
Epoch 88/100
188/188 [==============================] - 0s 113us/sample - loss: 7.8486e-04
Epoch 89/100
188/188 [==============================] - 0s 137us/sample - loss: 7.4506e-04
Epoch 90/100
188/188 [==============================] - 0s 144us/sample - loss: 6.9975e-04
Epoch 91/100
188/188 [==============================] - 0s 152us/sample - loss: 6.4877e-04
Epoch 92/100
188/188 [==============================] - 0s 133us/sample - loss: 6.4436e-04
Epoch 93/100
188/188 [==============================] - 0s 112us/sample - loss: 5.6517e-04
Epoch 94/100

188/188 [==============================] - 0s 107us/sample - loss: 5.8239e-04
Epoch 95/100
188/188 [==============================] - 0s 115us/sample - loss: 5.5286e-04
Epoch 96/100
188/188 [==============================] - 0s 110us/sample - loss: 5.0810e-04
Epoch 97/100
188/188 [==============================] - 0s 134us/sample - loss: 5.3482e-04
Epoch 98/100
188/188 [==============================] - 0s 137us/sample - loss: 5.1908e-04
Epoch 99/100
188/188 [==============================] - 0s 117us/sample - loss: 6.2931e-04
Epoch 100/100
188/188 [==============================] - 0s 105us/sample - loss: 5.7736e-04

In [111]:
# Evaluate the model using the test data - mean
#model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")
model_loss = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}")

63/1 - 0s - loss: 0.0094
Loss: 0.0122851375638256

In [112]:
#y_pred
y_pred_all

array([[ -6.39329145],
       [ -4.21477926],
       [ -5.40069087],
       [ -5.06740099],
       [ -2.25352759],
       [ -1.96319521],
       [ -6.81204761],
       [  0.09555198],
       [-29.69623222],
       [ -0.0376157 ],
       [ -8.9480084 ],
       [ -6.77066348],
       [-15.58020361],
       [ -2.8325493 ],
       [ -5.43634511],
       [ -9.05260604],
       [ -8.87639   ],
       [ -2.28007613],
       [ -3.28548302],
       [ -8.95677099],
       [ -2.75075224],
       [ -6.16809945],
       [ -4.12769886],
       [-15.69623358],
       [-10.02834512],
       [ -1.96319521],
       [ -8.56297534],
       [ -9.2246328 ],
       [-13.96080296],
       [  0.61291961],
       [ -4.03266573],
       [ -5.78167559],
       [ -8.28508654],
       [-12.47016706],
       [ -4.49033081],
       [ -1.96319521],
       [ -1.96319521],
       [ -2.3086612 ],
       [ -5.97317343],
       [ -3.94685048],
       [-12.3473811 ],
       [  0.61291961],
       [ -1.96319521],
       [ -8.44331316],
       [ -2.80100167],
       [ -2.80559969],
       [-13.0160579 ],
       [ -3.25568194],
       [ -4.89952099],
       [-17.24041984],
       [-17.76322201],
       [ -1.96319521],
       [ -4.19899132],
       [ -1.96319521],
       [ -2.30303117],
       [ -9.74358232],
       [ -3.91480113],
       [-15.93225636],
       [ -3.28573423],
       [ -4.72807571],
       [ -5.07877798],
       [  0.49580135],
       [ -2.99793047],
       [ -1.96319521],
       [-13.08392302],
       [ -6.30224298],
       [  0.61291961],
       [ -1.33868631],
       [ -2.0856178 ],
       [-10.84575285],
       [ -9.40869433],
       [ -0.6751378 ],
       [ -9.34544792],
       [ -4.11431631],
       [ -3.70190339],
       [ -8.42213661],
       [-12.55837389],
       [ -5.4198589 ],
       [ 13.12893327],
       [ -1.10449027],
       [ -7.8881412 ],
       [ -2.99793047],
       [ -2.50432112],
       [ -2.39787225],
       [  2.15429917],
       [ -2.8325493 ],
       [-12.41714278],
       [ -3.67204608],
       [-16.97199775],
       [ -5.52613771],
       [-13.21848294],
       [ -0.17099137],
       [ -6.84052854],
       [ -9.53143028],
       [ -4.58301496],
       [-25.40423373],
       [ -9.01533796],
       [ -1.96319521],
       [-10.01526135],
       [ -0.6751378 ],
       [ -9.3826757 ],
       [  0.03699285],
       [ -2.48056284],
       [ -1.44940202],
       [ -2.74535191],
       [-14.89274934],
       [-16.13658974],
       [ -1.10449027],
       [-11.44829505],
       [ -9.54843801],
       [ -1.96319521],
       [-10.26208552],
       [-20.46055687],
       [-15.35116919],
       [-11.49200211],
       [ -8.8473432 ],
       [ -8.65019949],
       [ -4.51374748],
       [-10.35341693],
       [ -1.96319521],
       [ -3.02168875],
       [ -4.57089196],
       [ -1.96319521],
       [ -0.81211526],
       [ -1.96319521],
       [ -7.96715623],
       [  0.61291961],
       [ -4.44826094],
       [ -9.065622  ],
       [ -6.01770304],
       [ -2.84971246],
       [ 13.12893327],
       [ -8.23819077],
       [-12.23067499],
       [-13.17776077],
       [ -4.28720423],
       [ -3.46002455],
       [ -6.20491001],
       [ -1.96319521],
       [ -4.35152792],
       [  1.78385876],
       [ -7.72852591],
       [ -2.39787225],
       [  0.61291961],
       [-11.15337547],
       [ -1.96319521],
       [ -2.51435285],
       [ -6.37294406],
       [-16.29555522],
       [ -7.31149153],
       [  5.53091272],
       [-16.13631645],
       [  0.61291961],
       [ -8.75594613],
       [-10.52162527],
       [ -1.96319521],
       [ -9.48982711],
       [ -3.65468173],
       [ -1.96319521],
       [ -8.26106039],
       [ -5.40347172],
       [ -1.96319521],
       [-11.29305695],
       [-12.71252763],
       [ -7.23174025],
       [ -7.22497006],
       [ -9.47106859],
       [ -5.48114323],
       [-29.34379293],
       [ -5.1500041 ],
       [ -3.26065609],
       [ -0.60134623],
       [ -6.91365741],
       [ -8.40108103],
       [ -6.66739537],
       [ -0.97439948],
       [-13.54341334],
       [-12.03376666],
       [ -3.94439935],
       [ -7.2788006 ],
       [ -1.19250543],
       [ -8.94200977],
       [ -5.5920667 ],
       [ -8.37422702],
       [ -9.89800217],
       [-11.25902984],
       [ -9.07084491],
       [ -1.96319521],
       [ -4.12769886],
       [ -3.04544704],
       [-12.85649906],
       [ -7.08377824],
       [ -4.16760743],
       [ -2.50432112],
       [  1.45632298],
       [-24.88596442],
       [-19.95854319],
       [-17.18708726],
       [ -2.68988377],
       [ -7.75302953],
       [-12.73874116],
       [-17.28961029],
       [ -1.96319521],
       [ -0.64418741],
       [ -4.8743606 ],
       [-16.06011075],
       [-10.23972964],
       [  0.72770154],
       [ -7.03745354],
       [-11.00197972],
       [ -8.83261054],
       [ -3.04544704],
       [ -0.24578533],
       [-20.19745189],
       [ -1.96319521],
       [ -2.39787225],
       [ -4.58301496],
       [ -1.96319521],
       [-28.57369715],
       [ -5.34203515],
       [ -3.02460687],
       [ -4.95734541],
       [-19.17103513],
       [ -1.96319521],
       [-12.87093573],
       [ -5.56060547],
       [-10.40566035],
       [ -3.94439935],
       [ -0.25643448],
       [-14.77138762],
       [-16.74821895],
       [ -8.38633766],
       [-10.66555373],
       [ -4.82820968],
       [ -1.97384436],
       [ -1.96319521],
       [-10.25581907],
       [ -7.08652966],
       [ -3.11441027],
       [-11.5947536 ],
       [ -7.18365526],
       [-10.58635556],
       [ -5.99187146],
       [-11.48272727],
       [-11.9585989 ],
       [ -2.99793047],
       [ -2.36323485],
       [ -3.27756359],
       [ -3.73848822],
       [ -3.70190339],
       [ -1.96319521]])

In [113]:
#np.rint(y_pred)
y_pred_all_clean = np.rint(y_pred_all)
y_pred_all_clean

array([[ -6.],
       [ -4.],
       [ -5.],
       [ -5.],
       [ -2.],
       [ -2.],
       [ -7.],
       [  0.],
       [-30.],
       [ -0.],
       [ -9.],
       [ -7.],
       [-16.],
       [ -3.],
       [ -5.],
       [ -9.],
       [ -9.],
       [ -2.],
       [ -3.],
       [ -9.],
       [ -3.],
       [ -6.],
       [ -4.],
       [-16.],
       [-10.],
       [ -2.],
       [ -9.],
       [ -9.],
       [-14.],
       [  1.],
       [ -4.],
       [ -6.],
       [ -8.],
       [-12.],
       [ -4.],
       [ -2.],
       [ -2.],
       [ -2.],
       [ -6.],
       [ -4.],
       [-12.],
       [  1.],
       [ -2.],
       [ -8.],
       [ -3.],
       [ -3.],
       [-13.],
       [ -3.],
       [ -5.],
       [-17.],
       [-18.],
       [ -2.],
       [ -4.],
       [ -2.],
       [ -2.],
       [-10.],
       [ -4.],
       [-16.],
       [ -3.],
       [ -5.],
       [ -5.],
       [  0.],
       [ -3.],
       [ -2.],
       [-13.],
       [ -6.],
       [  1.],
       [ -1.],
       [ -2.],
       [-11.],
       [ -9.],
       [ -1.],
       [ -9.],
       [ -4.],
       [ -4.],
       [ -8.],
       [-13.],
       [ -5.],
       [ 13.],
       [ -1.],
       [ -8.],
       [ -3.],
       [ -3.],
       [ -2.],
       [  2.],
       [ -3.],
       [-12.],
       [ -4.],
       [-17.],
       [ -6.],
       [-13.],
       [ -0.],
       [ -7.],
       [-10.],
       [ -5.],
       [-25.],
       [ -9.],
       [ -2.],
       [-10.],
       [ -1.],
       [ -9.],
       [  0.],
       [ -2.],
       [ -1.],
       [ -3.],
       [-15.],
       [-16.],
       [ -1.],
       [-11.],
       [-10.],
       [ -2.],
       [-10.],
       [-20.],
       [-15.],
       [-11.],
       [ -9.],
       [ -9.],
       [ -5.],
       [-10.],
       [ -2.],
       [ -3.],
       [ -5.],
       [ -2.],
       [ -1.],
       [ -2.],
       [ -8.],
       [  1.],
       [ -4.],
       [ -9.],
       [ -6.],
       [ -3.],
       [ 13.],
       [ -8.],
       [-12.],
       [-13.],
       [ -4.],
       [ -3.],
       [ -6.],
       [ -2.],
       [ -4.],
       [  2.],
       [ -8.],
       [ -2.],
       [  1.],
       [-11.],
       [ -2.],
       [ -3.],
       [ -6.],
       [-16.],
       [ -7.],
       [  6.],
       [-16.],
       [  1.],
       [ -9.],
       [-11.],
       [ -2.],
       [ -9.],
       [ -4.],
       [ -2.],
       [ -8.],
       [ -5.],
       [ -2.],
       [-11.],
       [-13.],
       [ -7.],
       [ -7.],
       [ -9.],
       [ -5.],
       [-29.],
       [ -5.],
       [ -3.],
       [ -1.],
       [ -7.],
       [ -8.],
       [ -7.],
       [ -1.],
       [-14.],
       [-12.],
       [ -4.],
       [ -7.],
       [ -1.],
       [ -9.],
       [ -6.],
       [ -8.],
       [-10.],
       [-11.],
       [ -9.],
       [ -2.],
       [ -4.],
       [ -3.],
       [-13.],
       [ -7.],
       [ -4.],
       [ -3.],
       [  1.],
       [-25.],
       [-20.],
       [-17.],
       [ -3.],
       [ -8.],
       [-13.],
       [-17.],
       [ -2.],
       [ -1.],
       [ -5.],
       [-16.],
       [-10.],
       [  1.],
       [ -7.],
       [-11.],
       [ -9.],
       [ -3.],
       [ -0.],
       [-20.],
       [ -2.],
       [ -2.],
       [ -5.],
       [ -2.],
       [-29.],
       [ -5.],
       [ -3.],
       [ -5.],
       [-19.],
       [ -2.],
       [-13.],
       [ -6.],
       [-10.],
       [ -4.],
       [ -0.],
       [-15.],
       [-17.],
       [ -8.],
       [-11.],
       [ -5.],
       [ -2.],
       [ -2.],
       [-10.],
       [ -7.],
       [ -3.],
       [-12.],
       [ -7.],
       [-11.],
       [ -6.],
       [-11.],
       [-12.],
       [ -3.],
       [ -2.],
       [ -3.],
       [ -4.],
       [ -4.],
       [ -2.]])

In [114]:
y_pred_all_clean[y_pred_all_clean <= 0] = 0
y_pred_all_clean

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [13.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 2.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [13.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 2.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 6.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [115]:
forward_players['Pred_Fls'] = y_pred_all_clean
forward_players

                Pred_Fls
Player
Aaron Connolly       0.0
Aaron Lennon         0.0
Aaron Mooy           0.0
Adam Idah            0.0
Adam Lallana         0.0
...                  ...
Yoshinori Mut≈ç       0.0
Yves Bissouma        0.0
√ârik Lamela          0.0
√âtienne Capoue       0.0
ƒ∞lkay G√ºndoƒüan       0.0

[251 rows x 1 columns]

In [116]:
pred_fls_df = forward_players
pred_fls_df

                Pred_Fls
Player
Aaron Connolly       0.0
Aaron Lennon         0.0
Aaron Mooy           0.0
Adam Idah            0.0
Adam Lallana         0.0
...                  ...
Yoshinori Mut≈ç       0.0
Yves Bissouma        0.0
√ârik Lamela          0.0
√âtienne Capoue       0.0
ƒ∞lkay G√ºndoƒüan       0.0

[251 rows x 1 columns]

In [117]:
pred_fls_df.to_csv('pred_fls.csv')

In [118]:
y_pred_nn = nn.predict(X_test_scaled)#X_scaler.transform(X))
y_pred_nn
pd.DataFrame({'y_pred_nn': y_pred_nn[:,0], 'y_test': y_test[:,0]})

    y_pred_nn    y_test
0    0.023354  0.000000
1    0.795896  0.710526
2    0.045876  0.000000
3    1.517048  1.643836
4    0.030425  0.000000
..        ...       ...
58   0.022585  0.000000
59   0.286560  0.416667
60   0.515261  0.442857
61   0.601215  0.666667
62   0.349211  0.333333

[63 rows x 2 columns]