In [76]:
import pandas as pd
import numpy as np
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from tensorflow import keras
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [77]:
player_data = pd.read_csv('/Users/hunter/Desktop/Data_Class/final_project/Data/cleaned_players.csv')

In [78]:
player_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
1,James Milner,CM,4.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Midfield,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20370,Riyad Mahrez,CM,90.0,1,2,0.1,0.1,0.5,2,2,...,1,4,1,1,0,0,2018,25.0,Midfield,PL
20371,Christian Fuchs,LB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,1,0,4,0,0,2018,2.0,Defender,PL
20372,Harry Maguire,CB,90.0,0,0,0.4,0.4,0.0,4,1,...,1,0,2,5,0,0,2018,8.0,Defender,PL
20373,Wes Morgan,CB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,3,0,0,2018,2.5,Defender,PL
20374,Hamza Choudhury,RB,34.0,0,0,0.0,0.0,0.0,1,0,...,1,0,0,4,1,0,2018,-0.5,Defender,PL

In [79]:
forward_data = player_data[player_data['Position Group'] == 'Forward']
forward_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
12,Teemu Pukki,FW,83.0,1,0,0.4,0.4,0.1,3,1,...,1,0,1,1,0,0,2019,15.0,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20353,Harry Kane,FW,90.0,2,0,0.2,0.2,0.0,3,2,...,0,0,0,0,0,0,2018,24.5,Forward,PL
20354,Lucas Moura,LW,74.0,0,1,0.1,0.1,0.0,2,0,...,2,0,0,0,0,0,2018,5.0,Forward,PL
20356,√ârik Lamela,RW,78.0,2,0,1.3,1.3,0.0,2,2,...,2,1,1,2,0,0,2018,26.5,Forward,PL
20361,Son Heung-min,FW,6.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2018,1.0,Forward,PL
20366,Jamie Vardy,FW,90.0,2,0,0.5,0.5,0.3,6,2,...,0,0,0,0,0,0,2018,25.0,Forward,PL

In [80]:
# Groupby player (forward) mean
forward_data_mean = forward_data.groupby(["Player"]).mean()
forward_data_mean.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [81]:
forward_players = forward_data_mean.filter(['Player'], axis=1)
forward_players

Empty DataFrame
Columns: []
Index: [Aaron Connolly, Aaron Lennon, Aaron Mooy, Adam Idah, Adam Lallana, Adam Smith, Adama Traor√©, Ahmed Elmohamady, Ainsley Maitland-Niles, Albian Ajeti, Alex Iwobi, Alex Oxlade-Chamberlain, Alexandre Lacazette, Alexis Mac Allister, Alireza Jahanbakhsh, Allan Saint-Maximin, Andre Gray, Andreas Pereira, Andriy Yarmolenko, Andros Townsend, Andy Carroll, Angel Gomes, Anthony Gordon, Anthony Martial, Anwar El Ghazi, Armando Broja, Arthur Masuaku, Ashley Barnes, Ayoze P√©rez, Ben Chilwell, Ben Osborn, Bernard, Bernardo, Bernardo Silva, Billy Sharp, Borja Bast√≥n, Brandon Williams, Bukayo Saka, Callum Hudson-Odoi, Callum Robinson, Callum Wilson, Calum Chambers, Carlos S√°nchez, Cenk Tosun, Che Adams, Cheikhou Kouyat√©, Chris Wood, Christian Atsu, Christian Benteke, Christian Eriksen, Christian Pulisic, Ciaran Clark, Connor Wickham, Conor Hourihane, Dan Gosling, Daniel James, Daniel Podence, Danny Ings, Danny Rose, Danny Welbeck, David McGoldrick, DeAndre Yedlin, Declan Rice, Dejan Lovren, Dele Alli, Demarai Gray, Dennis Srbeny, Diego Rico, Diogo Dalot, Diogo Jota, Divock Origi, Domingos Quina, Dominic Calvert-Lewin, Dominic Solanke, Douglas Luiz, Dwight Gayle, Dwight McNeil, Eddie Nketiah, Ederson, Emerson Palmieri, Emi Buend√≠a, Emil Krafth, Eric Dier, Ezequiel Schelotto, Fabinho, Faustino Anjorin, Felipe Anderson, Florin Andone, Gabriel Jesus, Georges-K√©vin N'Koudou, Gerard Deulofeu, Giovani Lo Celso, Glenn Murray, Gylfi Sigur√∞sson, Hamza Choudhury, Harry Kane, Harry Wilson, Harry Winks, Harvey Barnes, Henri Lansbury, ...]

[251 rows x 0 columns]

In [82]:
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_var, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

In [83]:
# Create target
y_var = forward_data_mean.Int
y_var.head()

Player
Aaron Connolly    0.000000
Aaron Lennon      0.500000
Aaron Mooy        0.384615
Adam Idah         0.000000
Adam Lallana      0.230769
Name: Int, dtype: float64

In [84]:
player_x = forward_data_mean.drop("Int", axis =1)
player_x.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.153846,0.0,2018.307692,1.230769

In [85]:
# Create features 
X = player_x
X.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.153846,0.0,2018.307692,1.230769

In [86]:
X_opt = X.iloc[:,:].values
X_opt

array([[4.93125000e+01, 1.25000000e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [7.36111111e+01, 5.55555556e-02, 5.55555556e-02, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [7.38461538e+01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [4.26969697e+01, 6.06060606e-02, 3.03030303e-02, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [9.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [87]:
y_var = y_var.reset_index().iloc[:,1:].values

In [88]:
# Test if features are siginiicant 
trimmed_X = backwardElimination(X_opt, 0.05)
trimmed_X

array([[1.25000000e-01, 0.00000000e+00, 1.43750000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [5.55555556e-02, 5.55555556e-02, 3.88888889e-01, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [0.00000000e+00, 0.00000000e+00, 1.38461538e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [6.06060606e-02, 3.03030303e-02, 1.09090909e+00, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [89]:
# Split our preprocessed data into our features and target arrays
y = y_var
X = trimmed_X

In [90]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [91]:
# Create scaler instance
scaler = StandardScaler()

In [92]:
# Fit the scaler
X_scaler = scaler.fit(X_train)

In [93]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [94]:
# Define the linear regression model
lin_reg = LinearRegression()

In [95]:
# Train the model
lin_reg.fit(X_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [96]:
lin_reg.score(X_train, y_train)

-2728.754232600888

In [97]:
lin_reg.score(X_test, y_test)

-2520.444825017611

In [98]:
y_pred = lin_reg.predict(X_test)

In [99]:
y_pred_all = lin_reg.predict(X)

In [100]:
r2_score(y_test, y_pred)

-2520.444825017611

In [101]:
# Define hidden layers
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 50

In [102]:
nn = tf.keras.models.Sequential()

In [103]:
# Hidden layer 1
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [104]:
# Hidden layer 2
nn.add(tf.keras.layers.Dense(units=hidden_layer2, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [105]:
# Output layer
nn.add(tf.keras.layers.Dense(units=1))

In [106]:
# Compile the model
nn.compile(loss="mean_squared_error", optimizer="adam")#, metrics=["accuracy"])

In [107]:
# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 50)                600
_________________________________________________________________
dense_7 (Dense)              (None, 50)                2550
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 51
=================================================================
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________

In [108]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Train on 188 samples
Epoch 1/100
188/188 [==============================] - 1s 4ms/sample - loss: 0.2429
Epoch 2/100
188/188 [==============================] - 0s 197us/sample - loss: 0.1924
Epoch 3/100
188/188 [==============================] - 0s 203us/sample - loss: 0.1612
Epoch 4/100
188/188 [==============================] - 0s 159us/sample - loss: 0.1470
Epoch 5/100
188/188 [==============================] - 0s 160us/sample - loss: 0.1367
Epoch 6/100
188/188 [==============================] - 0s 143us/sample - loss: 0.1283
Epoch 7/100
188/188 [==============================] - 0s 127us/sample - loss: 0.1237
Epoch 8/100
188/188 [==============================] - 0s 118us/sample - loss: 0.1199
Epoch 9/100
188/188 [==============================] - 0s 121us/sample - loss: 0.1176
Epoch 10/100
188/188 [==============================] - 0s 222us/sample - loss: 0.1149
Epoch 11/100
188/188 [==============================] - 0s 117us/sample - loss: 0.1120
Epoch 12/100
188/188 [==============================] - 0s 109us/sample - loss: 0.1098
Epoch 13/100
188/188 [==============================] - 0s 145us/sample - loss: 0.1077
Epoch 14/100
188/188 [==============================] - 0s 150us/sample - loss: 0.1056
Epoch 15/100
188/188 [==============================] - 0s 153us/sample - loss: 0.1037
Epoch 16/100
188/188 [==============================] - 0s 125us/sample - loss: 0.1015
Epoch 17/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0992
Epoch 18/100
188/188 [==============================] - 0s 154us/sample - loss: 0.0975
Epoch 19/100
188/188 [==============================] - 0s 133us/sample - loss: 0.0953
Epoch 20/100
188/188 [==============================] - 0s 132us/sample - loss: 0.0930
Epoch 21/100
188/188 [==============================] - 0s 153us/sample - loss: 0.0906
Epoch 22/100
188/188 [==============================] - 0s 155us/sample - loss: 0.0884
Epoch 23/100
188/188 [==============================] - 0s 177us/sample - loss: 0.0863
Epoch 24/100
188/188 [==============================] - 0s 173us/sample - loss: 0.0843
Epoch 25/100
188/188 [==============================] - 0s 144us/sample - loss: 0.0825
Epoch 26/100
188/188 [==============================] - 0s 147us/sample - loss: 0.0796
Epoch 27/100
188/188 [==============================] - 0s 120us/sample - loss: 0.0766
Epoch 28/100
188/188 [==============================] - 0s 127us/sample - loss: 0.0739
Epoch 29/100
188/188 [==============================] - 0s 119us/sample - loss: 0.0731
Epoch 30/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0705
Epoch 31/100
188/188 [==============================] - 0s 127us/sample - loss: 0.0686
Epoch 32/100
188/188 [==============================] - 0s 120us/sample - loss: 0.0666
Epoch 33/100
188/188 [==============================] - 0s 143us/sample - loss: 0.0647
Epoch 34/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0632
Epoch 35/100
188/188 [==============================] - 0s 142us/sample - loss: 0.0622
Epoch 36/100
188/188 [==============================] - 0s 142us/sample - loss: 0.0606
Epoch 37/100
188/188 [==============================] - 0s 124us/sample - loss: 0.0607
Epoch 38/100
188/188 [==============================] - 0s 146us/sample - loss: 0.0571
Epoch 39/100
188/188 [==============================] - 0s 108us/sample - loss: 0.0560
Epoch 40/100
188/188 [==============================] - 0s 124us/sample - loss: 0.0538
Epoch 41/100
188/188 [==============================] - 0s 155us/sample - loss: 0.0530
Epoch 42/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0512
Epoch 43/100
188/188 [==============================] - 0s 150us/sample - loss: 0.0514
Epoch 44/100
188/188 [==============================] - 0s 116us/sample - loss: 0.0505
Epoch 45/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0480
Epoch 46/100
188/188 [==============================] - 0s 152us/sample - loss: 0.0478
Epoch 47/100
188/188 [==============================] - 0s 121us/sample - loss: 0.0472
Epoch 48/100
188/188 [==============================] - 0s 155us/sample - loss: 0.0457
Epoch 49/100
188/188 [==============================] - 0s 133us/sample - loss: 0.0432
Epoch 50/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0422
Epoch 51/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0405
Epoch 52/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0398
Epoch 53/100
188/188 [==============================] - 0s 136us/sample - loss: 0.0385
Epoch 54/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0369
Epoch 55/100
188/188 [==============================] - 0s 139us/sample - loss: 0.0374
Epoch 56/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0418
Epoch 57/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0379
Epoch 58/100
188/188 [==============================] - 0s 122us/sample - loss: 0.0367
Epoch 59/100
188/188 [==============================] - 0s 119us/sample - loss: 0.0337
Epoch 60/100
188/188 [==============================] - 0s 116us/sample - loss: 0.0335
Epoch 61/100
188/188 [==============================] - 0s 121us/sample - loss: 0.0292
Epoch 62/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0287
Epoch 63/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0279
Epoch 64/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0270
Epoch 65/100
188/188 [==============================] - 0s 110us/sample - loss: 0.0259
Epoch 66/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0246
Epoch 67/100
188/188 [==============================] - 0s 96us/sample - loss: 0.0236
Epoch 68/100
188/188 [==============================] - 0s 129us/sample - loss: 0.0231
Epoch 69/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0218
Epoch 70/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0214
Epoch 71/100
188/188 [==============================] - 0s 121us/sample - loss: 0.0213
Epoch 72/100
188/188 [==============================] - 0s 113us/sample - loss: 0.0207
Epoch 73/100
188/188 [==============================] - 0s 106us/sample - loss: 0.0208
Epoch 74/100
188/188 [==============================] - 0s 115us/sample - loss: 0.0195
Epoch 75/100
188/188 [==============================] - 0s 105us/sample - loss: 0.0188
Epoch 76/100
188/188 [==============================] - 0s 117us/sample - loss: 0.0169
Epoch 77/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0170
Epoch 78/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0157
Epoch 79/100
188/188 [==============================] - 0s 109us/sample - loss: 0.0148
Epoch 80/100
188/188 [==============================] - 0s 114us/sample - loss: 0.0142
Epoch 81/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0134
Epoch 82/100
188/188 [==============================] - 0s 111us/sample - loss: 0.0135
Epoch 83/100
188/188 [==============================] - 0s 120us/sample - loss: 0.0119
Epoch 84/100
188/188 [==============================] - 0s 109us/sample - loss: 0.0124
Epoch 85/100
188/188 [==============================] - 0s 117us/sample - loss: 0.0113
Epoch 86/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0115
Epoch 87/100
188/188 [==============================] - 0s 106us/sample - loss: 0.0103
Epoch 88/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0099
Epoch 89/100
188/188 [==============================] - 0s 122us/sample - loss: 0.0094
Epoch 90/100
188/188 [==============================] - 0s 129us/sample - loss: 0.0088
Epoch 91/100
188/188 [==============================] - 0s 126us/sample - loss: 0.0086
Epoch 92/100
188/188 [==============================] - 0s 124us/sample - loss: 0.0082
Epoch 93/100
188/188 [==============================] - 0s 123us/sample - loss: 0.0082
Epoch 94/100
188/188 [==============================] - 0s 107us/sample - loss: 0.0080
Epoch 95/100

188/188 [==============================] - 0s 112us/sample - loss: 0.0070
Epoch 96/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0071
Epoch 97/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0064
Epoch 98/100
188/188 [==============================] - 0s 105us/sample - loss: 0.0072
Epoch 99/100
188/188 [==============================] - 0s 97us/sample - loss: 0.0068
Epoch 100/100
188/188 [==============================] - 0s 98us/sample - loss: 0.0065

In [109]:
# Evaluate the model using the test data - mean
#model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")
model_loss = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}")

63/1 - 0s - loss: 1.8546
Loss: 1.8439108795589871

In [110]:
#y_pred.shape
y_pred_all.shape

(251, 1)

In [111]:
#y_pred
y_pred_all

array([[ 15.48588009],
       [ 11.21904229],
       [ 13.3130275 ],
       [ 12.08899674],
       [  6.65317333],
       [  5.65267712],
       [ 16.98089774],
       [  2.32149566],
       [ 64.03465099],
       [  2.74314919],
       [ 20.54302982],
       [ 16.21422614],
       [ 35.25488017],
       [  7.46322186],
       [ 13.74807642],
       [ 21.16292826],
       [ 20.44116975],
       [  7.07604219],
       [  9.24247216],
       [ 20.76663736],
       [  8.5479998 ],
       [ 14.38175228],
       [ 10.99782843],
       [ 34.84755822],
       [ 23.18726211],
       [  5.65267712],
       [ 19.82326576],
       [ 22.24849455],
       [ 32.1830384 ],
       [  1.24877572],
       [  9.94355687],
       [ 14.43824059],
       [ 19.1997678 ],
       [ 28.22297879],
       [ 11.59500357],
       [  5.65267712],
       [  5.65267712],
       [  7.32994731],
       [ 14.48191039],
       [ 10.61179769],
       [ 28.6377235 ],
       [  1.24877572],
       [  5.65267712],
       [ 20.12384438],
       [  8.0339729 ],
       [  8.00023525],
       [ 29.37445454],
       [  8.85574682],
       [ 13.07604515],
       [ 37.97002769],
       [ 38.85885751],
       [  5.65267712],
       [ 10.98416875],
       [  5.65267712],
       [  6.74431589],
       [ 22.2926499 ],
       [ 10.13579752],
       [ 35.45980578],
       [  9.07789399],
       [ 11.85527972],
       [ 13.28400761],
       [  0.53762148],
       [  7.798117  ],
       [  5.65267712],
       [ 29.77338215],
       [ 15.11651253],
       [  1.24877572],
       [  5.73189612],
       [  6.59755899],
       [ 25.29061332],
       [ 21.32992813],
       [  3.45072642],
       [ 22.33210123],
       [ 10.6497029 ],
       [  9.2737666 ],
       [ 19.68980306],
       [ 29.09561541],
       [ 13.44454006],
       [-25.43042332],
       [  4.18470999],
       [ 19.03828301],
       [  7.798117  ],
       [  6.98896495],
       [  6.55794949],
       [ -1.00968581],
       [  7.46322186],
       [ 28.35021281],
       [ 10.44178987],
       [ 37.56402321],
       [ 13.08291422],
       [ 30.00708904],
       [  2.80016993],
       [ 17.39366899],
       [ 22.2677375 ],
       [ 11.08993464],
       [ 55.31920771],
       [ 20.72932257],
       [  5.65267712],
       [ 22.77444328],
       [  3.45072642],
       [ 21.94119118],
       [  1.96591854],
       [  6.72539706],
       [  4.89985661],
       [  8.07608493],
       [ 33.34265628],
       [ 35.91777247],
       [  4.18470999],
       [ 26.1280398 ],
       [ 22.90298541],
       [  5.65267712],
       [ 23.57730769],
       [ 44.66983236],
       [ 33.85738523],
       [ 25.90501671],
       [ 20.93184504],
       [ 20.0959473 ],
       [ 11.96960847],
       [ 23.96795063],
       [  5.65267712],
       [  8.06168489],
       [ 12.05551267],
       [  5.65267712],
       [  3.45009248],
       [  5.65267712],
       [ 19.84426952],
       [  1.24877572],
       [ 11.09649599],
       [ 21.83405376],
       [ 14.24585985],
       [  7.72424106],
       [-25.43042332],
       [ 19.14535777],
       [ 27.31494253],
       [ 29.84509902],
       [ 11.32472943],
       [  8.99855731],
       [ 15.39990739],
       [  5.65267712],
       [ 10.9499451 ],
       [ -1.66432922],
       [ 18.1819391 ],
       [  6.55794949],
       [  1.24877572],
       [ 25.72003743],
       [  5.65267712],
       [  8.42401767],
       [ 15.43351558],
       [ 36.34881877],
       [ 17.5960823 ],
       [ -8.98133556],
       [ 35.77581139],
       [  1.24877572],
       [ 20.47305073],
       [ 23.70848736],
       [  5.65267712],
       [ 22.9936109 ],
       [ 11.16121343],
       [  5.65267712],
       [ 18.99746558],
       [ 13.43609431],
       [  5.65267712],
       [ 25.22998027],
       [ 28.44697991],
       [ 17.08947955],
       [ 17.92617907],
       [ 21.62908393],
       [ 14.02767168],
       [ 63.0716404 ],
       [ 13.33457169],
       [  8.83086964],
       [  3.77446708],
       [ 17.06264505],
       [ 19.55136812],
       [ 16.40587349],
       [  3.73701349],
       [ 30.67506966],
       [ 27.09338101],
       [  9.76939867],
       [ 17.37136335],
       [  4.52344636],
       [ 20.66651664],
       [ 13.87342993],
       [ 19.98699003],
       [ 22.88125958],
       [ 26.00871057],
       [ 20.89540152],
       [  5.65267712],
       [ 10.99782843],
       [  8.32525278],
       [ 29.01246212],
       [ 17.01024831],
       [ 10.88168343],
       [  6.98896495],
       [  0.39288208],
       [ 53.59482547],
       [ 44.24608687],
       [ 38.54481554],
       [  7.83085131],
       [ 19.62711914],
       [ 29.13766189],
       [ 38.01455559],
       [  5.65267712],
       [  4.04610226],
       [ 12.45232623],
       [ 36.23123858],
       [ 23.73678553],
       [  1.35230425],
       [ 16.19229702],
       [ 24.7701894 ],
       [ 20.77894462],
       [  8.32525278],
       [  2.71674286],
       [ 44.67709113],
       [  5.65267712],
       [  6.55794949],
       [ 11.08993464],
       [  5.65267712],
       [ 61.40900929],
       [ 13.95799934],
       [  8.81581752],
       [ 13.17226491],
       [ 41.87037904],
       [  5.65267712],
       [ 29.16603502],
       [ 13.75836099],
       [ 24.80631203],
       [  9.76939867],
       [  3.05932046],
       [ 32.83623252],
       [ 37.17779488],
       [ 19.42686465],
       [ 24.70885266],
       [ 11.90880372],
       [  5.99525473],
       [  5.65267712],
       [ 24.00841531],
       [ 17.451528  ],
       [ 10.77178512],
       [ 26.2611391 ],
       [ 18.47837862],
       [ 25.00881605],
       [ 15.39256198],
       [ 25.93298144],
       [ 27.14720602],
       [  7.798117  ],
       [  7.30922027],
       [  9.1546162 ],
       [ 10.44573527],
       [  9.2737666 ],
       [  5.65267712]])

In [112]:
#np.rint(y_pred)
y_pred_all_clean = np.rint(y_pred_all)
y_pred_all_clean

array([[ 15.],
       [ 11.],
       [ 13.],
       [ 12.],
       [  7.],
       [  6.],
       [ 17.],
       [  2.],
       [ 64.],
       [  3.],
       [ 21.],
       [ 16.],
       [ 35.],
       [  7.],
       [ 14.],
       [ 21.],
       [ 20.],
       [  7.],
       [  9.],
       [ 21.],
       [  9.],
       [ 14.],
       [ 11.],
       [ 35.],
       [ 23.],
       [  6.],
       [ 20.],
       [ 22.],
       [ 32.],
       [  1.],
       [ 10.],
       [ 14.],
       [ 19.],
       [ 28.],
       [ 12.],
       [  6.],
       [  6.],
       [  7.],
       [ 14.],
       [ 11.],
       [ 29.],
       [  1.],
       [  6.],
       [ 20.],
       [  8.],
       [  8.],
       [ 29.],
       [  9.],
       [ 13.],
       [ 38.],
       [ 39.],
       [  6.],
       [ 11.],
       [  6.],
       [  7.],
       [ 22.],
       [ 10.],
       [ 35.],
       [  9.],
       [ 12.],
       [ 13.],
       [  1.],
       [  8.],
       [  6.],
       [ 30.],
       [ 15.],
       [  1.],
       [  6.],
       [  7.],
       [ 25.],
       [ 21.],
       [  3.],
       [ 22.],
       [ 11.],
       [  9.],
       [ 20.],
       [ 29.],
       [ 13.],
       [-25.],
       [  4.],
       [ 19.],
       [  8.],
       [  7.],
       [  7.],
       [ -1.],
       [  7.],
       [ 28.],
       [ 10.],
       [ 38.],
       [ 13.],
       [ 30.],
       [  3.],
       [ 17.],
       [ 22.],
       [ 11.],
       [ 55.],
       [ 21.],
       [  6.],
       [ 23.],
       [  3.],
       [ 22.],
       [  2.],
       [  7.],
       [  5.],
       [  8.],
       [ 33.],
       [ 36.],
       [  4.],
       [ 26.],
       [ 23.],
       [  6.],
       [ 24.],
       [ 45.],
       [ 34.],
       [ 26.],
       [ 21.],
       [ 20.],
       [ 12.],
       [ 24.],
       [  6.],
       [  8.],
       [ 12.],
       [  6.],
       [  3.],
       [  6.],
       [ 20.],
       [  1.],
       [ 11.],
       [ 22.],
       [ 14.],
       [  8.],
       [-25.],
       [ 19.],
       [ 27.],
       [ 30.],
       [ 11.],
       [  9.],
       [ 15.],
       [  6.],
       [ 11.],
       [ -2.],
       [ 18.],
       [  7.],
       [  1.],
       [ 26.],
       [  6.],
       [  8.],
       [ 15.],
       [ 36.],
       [ 18.],
       [ -9.],
       [ 36.],
       [  1.],
       [ 20.],
       [ 24.],
       [  6.],
       [ 23.],
       [ 11.],
       [  6.],
       [ 19.],
       [ 13.],
       [  6.],
       [ 25.],
       [ 28.],
       [ 17.],
       [ 18.],
       [ 22.],
       [ 14.],
       [ 63.],
       [ 13.],
       [  9.],
       [  4.],
       [ 17.],
       [ 20.],
       [ 16.],
       [  4.],
       [ 31.],
       [ 27.],
       [ 10.],
       [ 17.],
       [  5.],
       [ 21.],
       [ 14.],
       [ 20.],
       [ 23.],
       [ 26.],
       [ 21.],
       [  6.],
       [ 11.],
       [  8.],
       [ 29.],
       [ 17.],
       [ 11.],
       [  7.],
       [  0.],
       [ 54.],
       [ 44.],
       [ 39.],
       [  8.],
       [ 20.],
       [ 29.],
       [ 38.],
       [  6.],
       [  4.],
       [ 12.],
       [ 36.],
       [ 24.],
       [  1.],
       [ 16.],
       [ 25.],
       [ 21.],
       [  8.],
       [  3.],
       [ 45.],
       [  6.],
       [  7.],
       [ 11.],
       [  6.],
       [ 61.],
       [ 14.],
       [  9.],
       [ 13.],
       [ 42.],
       [  6.],
       [ 29.],
       [ 14.],
       [ 25.],
       [ 10.],
       [  3.],
       [ 33.],
       [ 37.],
       [ 19.],
       [ 25.],
       [ 12.],
       [  6.],
       [  6.],
       [ 24.],
       [ 17.],
       [ 11.],
       [ 26.],
       [ 18.],
       [ 25.],
       [ 15.],
       [ 26.],
       [ 27.],
       [  8.],
       [  7.],
       [  9.],
       [ 10.],
       [  9.],
       [  6.]])

In [113]:
y_pred_all_clean[y_pred_all_clean <= 0] = 0
y_pred_all_clean

array([[15.],
       [11.],
       [13.],
       [12.],
       [ 7.],
       [ 6.],
       [17.],
       [ 2.],
       [64.],
       [ 3.],
       [21.],
       [16.],
       [35.],
       [ 7.],
       [14.],
       [21.],
       [20.],
       [ 7.],
       [ 9.],
       [21.],
       [ 9.],
       [14.],
       [11.],
       [35.],
       [23.],
       [ 6.],
       [20.],
       [22.],
       [32.],
       [ 1.],
       [10.],
       [14.],
       [19.],
       [28.],
       [12.],
       [ 6.],
       [ 6.],
       [ 7.],
       [14.],
       [11.],
       [29.],
       [ 1.],
       [ 6.],
       [20.],
       [ 8.],
       [ 8.],
       [29.],
       [ 9.],
       [13.],
       [38.],
       [39.],
       [ 6.],
       [11.],
       [ 6.],
       [ 7.],
       [22.],
       [10.],
       [35.],
       [ 9.],
       [12.],
       [13.],
       [ 1.],
       [ 8.],
       [ 6.],
       [30.],
       [15.],
       [ 1.],
       [ 6.],
       [ 7.],
       [25.],
       [21.],
       [ 3.],
       [22.],
       [11.],
       [ 9.],
       [20.],
       [29.],
       [13.],
       [ 0.],
       [ 4.],
       [19.],
       [ 8.],
       [ 7.],
       [ 7.],
       [ 0.],
       [ 7.],
       [28.],
       [10.],
       [38.],
       [13.],
       [30.],
       [ 3.],
       [17.],
       [22.],
       [11.],
       [55.],
       [21.],
       [ 6.],
       [23.],
       [ 3.],
       [22.],
       [ 2.],
       [ 7.],
       [ 5.],
       [ 8.],
       [33.],
       [36.],
       [ 4.],
       [26.],
       [23.],
       [ 6.],
       [24.],
       [45.],
       [34.],
       [26.],
       [21.],
       [20.],
       [12.],
       [24.],
       [ 6.],
       [ 8.],
       [12.],
       [ 6.],
       [ 3.],
       [ 6.],
       [20.],
       [ 1.],
       [11.],
       [22.],
       [14.],
       [ 8.],
       [ 0.],
       [19.],
       [27.],
       [30.],
       [11.],
       [ 9.],
       [15.],
       [ 6.],
       [11.],
       [ 0.],
       [18.],
       [ 7.],
       [ 1.],
       [26.],
       [ 6.],
       [ 8.],
       [15.],
       [36.],
       [18.],
       [ 0.],
       [36.],
       [ 1.],
       [20.],
       [24.],
       [ 6.],
       [23.],
       [11.],
       [ 6.],
       [19.],
       [13.],
       [ 6.],
       [25.],
       [28.],
       [17.],
       [18.],
       [22.],
       [14.],
       [63.],
       [13.],
       [ 9.],
       [ 4.],
       [17.],
       [20.],
       [16.],
       [ 4.],
       [31.],
       [27.],
       [10.],
       [17.],
       [ 5.],
       [21.],
       [14.],
       [20.],
       [23.],
       [26.],
       [21.],
       [ 6.],
       [11.],
       [ 8.],
       [29.],
       [17.],
       [11.],
       [ 7.],
       [ 0.],
       [54.],
       [44.],
       [39.],
       [ 8.],
       [20.],
       [29.],
       [38.],
       [ 6.],
       [ 4.],
       [12.],
       [36.],
       [24.],
       [ 1.],
       [16.],
       [25.],
       [21.],
       [ 8.],
       [ 3.],
       [45.],
       [ 6.],
       [ 7.],
       [11.],
       [ 6.],
       [61.],
       [14.],
       [ 9.],
       [13.],
       [42.],
       [ 6.],
       [29.],
       [14.],
       [25.],
       [10.],
       [ 3.],
       [33.],
       [37.],
       [19.],
       [25.],
       [12.],
       [ 6.],
       [ 6.],
       [24.],
       [17.],
       [11.],
       [26.],
       [18.],
       [25.],
       [15.],
       [26.],
       [27.],
       [ 8.],
       [ 7.],
       [ 9.],
       [10.],
       [ 9.],
       [ 6.]])

In [114]:
forward_players['Pred_Int'] = y_pred_all_clean
forward_players

                Pred_Int
Player
Aaron Connolly      15.0
Aaron Lennon        11.0
Aaron Mooy          13.0
Adam Idah           12.0
Adam Lallana         7.0
...                  ...
Yoshinori Mut≈ç       7.0
Yves Bissouma        9.0
√ârik Lamela         10.0
√âtienne Capoue       9.0
ƒ∞lkay G√ºndoƒüan       6.0

[251 rows x 1 columns]

In [115]:
pred_int_df = forward_players
pred_int_df

                Pred_Int
Player
Aaron Connolly      15.0
Aaron Lennon        11.0
Aaron Mooy          13.0
Adam Idah           12.0
Adam Lallana         7.0
...                  ...
Yoshinori Mut≈ç       7.0
Yves Bissouma        9.0
√ârik Lamela         10.0
√âtienne Capoue       9.0
ƒ∞lkay G√ºndoƒüan       6.0

[251 rows x 1 columns]

In [116]:
pred_int_df.to_csv('pred_int.csv')

In [117]:
y_pred_nn = nn.predict(X_test_scaled)#X_scaler.transform(X))
y_pred_nn
pd.DataFrame({'y_pred_nn': y_pred_nn[:,0], 'y_test': y_test[:,0]})

    y_pred_nn    y_test
0    7.480401  0.000000
1    0.322571  0.000000
2    0.214792  0.222222
3    0.376599  0.666667
4    0.555126  0.279070
..        ...       ...
58   0.234125  0.000000
59   0.015790  0.103448
60   0.360686  0.150000
61   0.903313  1.000000
62   0.403554  1.000000

[63 rows x 2 columns]