In [77]:
import pandas as pd
import numpy as np
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from tensorflow import keras
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [78]:
player_data = pd.read_csv('/Users/hunter/Desktop/Data_Class/final_project/Data/cleaned_players.csv')

In [79]:
player_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
1,James Milner,CM,4.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Midfield,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20370,Riyad Mahrez,CM,90.0,1,2,0.1,0.1,0.5,2,2,...,1,4,1,1,0,0,2018,25.0,Midfield,PL
20371,Christian Fuchs,LB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,1,0,4,0,0,2018,2.0,Defender,PL
20372,Harry Maguire,CB,90.0,0,0,0.4,0.4,0.0,4,1,...,1,0,2,5,0,0,2018,8.0,Defender,PL
20373,Wes Morgan,CB,90.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,3,0,0,2018,2.5,Defender,PL
20374,Hamza Choudhury,RB,34.0,0,0,0.0,0.0,0.0,1,0,...,1,0,0,4,1,0,2018,-0.5,Defender,PL

In [80]:
forward_data = player_data[player_data['Position Group'] == 'Forward']
forward_data

,Player,Pos,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,...,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points,Position Group,League
0,Roberto Firmino,FW,86.0,0,1,0.9,0.9,0.4,4,1,...,1,0,1,0,0,0,2019,10.0,Forward,PL
2,Divock Origi,LW,74.0,1,0,0.2,0.2,0.0,1,1,...,2,4,3,1,0,0,2019,15.0,Forward,PL
3,Sadio Man√©,LW,16.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2019,1.0,Forward,PL
4,Mohamed Salah,RW,90.0,1,1,0.3,0.3,0.2,2,1,...,1,7,0,0,0,0,2019,17.5,Forward,PL
12,Teemu Pukki,FW,83.0,1,0,0.4,0.4,0.1,3,1,...,1,0,1,1,0,0,2019,15.0,Forward,PL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20353,Harry Kane,FW,90.0,2,0,0.2,0.2,0.0,3,2,...,0,0,0,0,0,0,2018,24.5,Forward,PL
20354,Lucas Moura,LW,74.0,0,1,0.1,0.1,0.0,2,0,...,2,0,0,0,0,0,2018,5.0,Forward,PL
20356,√ârik Lamela,RW,78.0,2,0,1.3,1.3,0.0,2,2,...,2,1,1,2,0,0,2018,26.5,Forward,PL
20361,Son Heung-min,FW,6.0,0,0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,2018,1.0,Forward,PL
20366,Jamie Vardy,FW,90.0,2,0,0.5,0.5,0.3,6,2,...,0,0,0,0,0,0,2018,25.0,Forward,PL

In [81]:
# Groupby player (forward) mean
forward_data_mean = forward_data.groupby(["Player"]).mean()
forward_data_mean.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,CrdR,year,fantasy_points
Player,,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,0.0,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,0.0,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,0.0,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.0,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,0.0,2018.307692,1.230769

In [82]:
forward_players = forward_data_mean.filter(['Player'], axis=1)
forward_players

Empty DataFrame
Columns: []
Index: [Aaron Connolly, Aaron Lennon, Aaron Mooy, Adam Idah, Adam Lallana, Adam Smith, Adama Traor√©, Ahmed Elmohamady, Ainsley Maitland-Niles, Albian Ajeti, Alex Iwobi, Alex Oxlade-Chamberlain, Alexandre Lacazette, Alexis Mac Allister, Alireza Jahanbakhsh, Allan Saint-Maximin, Andre Gray, Andreas Pereira, Andriy Yarmolenko, Andros Townsend, Andy Carroll, Angel Gomes, Anthony Gordon, Anthony Martial, Anwar El Ghazi, Armando Broja, Arthur Masuaku, Ashley Barnes, Ayoze P√©rez, Ben Chilwell, Ben Osborn, Bernard, Bernardo, Bernardo Silva, Billy Sharp, Borja Bast√≥n, Brandon Williams, Bukayo Saka, Callum Hudson-Odoi, Callum Robinson, Callum Wilson, Calum Chambers, Carlos S√°nchez, Cenk Tosun, Che Adams, Cheikhou Kouyat√©, Chris Wood, Christian Atsu, Christian Benteke, Christian Eriksen, Christian Pulisic, Ciaran Clark, Connor Wickham, Conor Hourihane, Dan Gosling, Daniel James, Daniel Podence, Danny Ings, Danny Rose, Danny Welbeck, David McGoldrick, DeAndre Yedlin, Declan Rice, Dejan Lovren, Dele Alli, Demarai Gray, Dennis Srbeny, Diego Rico, Diogo Dalot, Diogo Jota, Divock Origi, Domingos Quina, Dominic Calvert-Lewin, Dominic Solanke, Douglas Luiz, Dwight Gayle, Dwight McNeil, Eddie Nketiah, Ederson, Emerson Palmieri, Emi Buend√≠a, Emil Krafth, Eric Dier, Ezequiel Schelotto, Fabinho, Faustino Anjorin, Felipe Anderson, Florin Andone, Gabriel Jesus, Georges-K√©vin N'Koudou, Gerard Deulofeu, Giovani Lo Celso, Glenn Murray, Gylfi Sigur√∞sson, Hamza Choudhury, Harry Kane, Harry Wilson, Harry Winks, Harvey Barnes, Henri Lansbury, ...]

[251 rows x 0 columns]

In [83]:
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_var, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

In [84]:
# Create target
y_var = forward_data_mean.CrdR
y_var.head()

Player
Aaron Connolly    0.0
Aaron Lennon      0.0
Aaron Mooy        0.0
Adam Idah         0.0
Adam Lallana      0.0
Name: CrdR, dtype: float64

In [85]:
player_x = forward_data_mean.drop("CrdR", axis =1)
player_x.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,2018.307692,1.230769

In [86]:
# Create features 
X = player_x
X.head()

,Min,Gls,Ast,xG,npxG,xA,Sh,SoT,Fls,Fld,Crs,TklW,Int,CrdY,year,fantasy_points
Player,,,,,,,,,,,,,,,,
Aaron Connolly,49.312500,0.125000,0.000000,0.137500,0.137500,0.012500,1.437500,0.500000,0.687500,1.625000,0.437500,0.250000,0.000000,0.000000,2019.187500,3.156250
Aaron Lennon,73.611111,0.055556,0.055556,0.016667,0.016667,0.050000,0.388889,0.166667,0.722222,1.055556,1.777778,0.888889,0.500000,0.055556,2017.611111,2.138889
Aaron Mooy,73.846154,0.000000,0.000000,0.053846,0.053846,0.207692,1.384615,0.615385,0.384615,0.615385,5.923077,1.461538,0.384615,0.153846,2018.846154,2.846154
Adam Idah,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,0.000000,0.000000,2020.000000,2.500000
Adam Lallana,23.076923,0.000000,0.076923,0.046154,0.046154,0.023077,0.461538,0.000000,0.307692,0.692308,0.538462,0.230769,0.230769,0.153846,2018.307692,1.230769

In [87]:
X_opt = X.iloc[:,:].values
X_opt

array([[4.93125000e+01, 1.25000000e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [7.36111111e+01, 5.55555556e-02, 5.55555556e-02, ...,
        5.55555556e-02, 2.01761111e+03, 2.13888889e+00],
       [7.38461538e+01, 0.00000000e+00, 0.00000000e+00, ...,
        1.53846154e-01, 2.01884615e+03, 2.84615385e+00],
       ...,
       [4.26969697e+01, 6.06060606e-02, 3.03030303e-02, ...,
        1.21212121e-01, 2.01833333e+03, 2.06060606e+00],
       [9.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [88]:
y_var = y_var.reset_index().iloc[:,1:].values

In [89]:
# Test if features are siginiicant 
trimmed_X = backwardElimination(X_opt, 0.05)
trimmed_X

array([[1.25000000e-01, 0.00000000e+00, 1.43750000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [5.55555556e-02, 5.55555556e-02, 3.88888889e-01, ...,
        5.55555556e-02, 2.01761111e+03, 2.13888889e+00],
       [0.00000000e+00, 0.00000000e+00, 1.38461538e+00, ...,
        1.53846154e-01, 2.01884615e+03, 2.84615385e+00],
       ...,
       [6.06060606e-02, 3.03030303e-02, 1.09090909e+00, ...,
        1.21212121e-01, 2.01833333e+03, 2.06060606e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [90]:
# Split our preprocessed data into our features and target arrays
y = y_var
X = trimmed_X

In [91]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [92]:
# Create scaler instance
scaler = StandardScaler()

In [93]:
# Fit the scaler
X_scaler = scaler.fit(X_train)

In [94]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [95]:
# Define the linear regression model
lin_reg = LinearRegression()

In [96]:
# Train the model
lin_reg.fit(X_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [97]:
lin_reg.score(X_train, y_train)

-455.1302701257231

In [98]:
lin_reg.score(X_test, y_test)

-300999.11587251705

In [99]:
y_pred = lin_reg.predict(X_test)

In [100]:
y_pred_all = lin_reg.predict(X)

In [101]:
r2_score(y_test, y_pred)

-300999.11587251705

In [102]:
# Define hidden layers
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 50

In [103]:
nn = tf.keras.models.Sequential()

In [104]:
# Hidden layer 1
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [105]:
# Hidden layer 2
nn.add(tf.keras.layers.Dense(units=hidden_layer2, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [106]:
# Output layer
nn.add(tf.keras.layers.Dense(units=1))

In [107]:
# Compile the model
nn.compile(loss="mean_squared_error", optimizer="adam")#, metrics=["accuracy"])

In [108]:
# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 50)                600
_________________________________________________________________
dense_7 (Dense)              (None, 50)                2550
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 51
=================================================================
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________

In [109]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Train on 188 samples
Epoch 1/100
188/188 [==============================] - 1s 4ms/sample - loss: 0.0136
Epoch 2/100
188/188 [==============================] - 0s 141us/sample - loss: 0.0104
Epoch 3/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0098
Epoch 4/100
188/188 [==============================] - 0s 146us/sample - loss: 0.0088
Epoch 5/100
188/188 [==============================] - 0s 167us/sample - loss: 0.0083
Epoch 6/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0077
Epoch 7/100
188/188 [==============================] - 0s 143us/sample - loss: 0.0072
Epoch 8/100
188/188 [==============================] - 0s 143us/sample - loss: 0.0068
Epoch 9/100
188/188 [==============================] - 0s 148us/sample - loss: 0.0065
Epoch 10/100
188/188 [==============================] - 0s 131us/sample - loss: 0.0059
Epoch 11/100
188/188 [==============================] - 0s 132us/sample - loss: 0.0055
Epoch 12/100
188/188 [==============================] - 0s 144us/sample - loss: 0.0049
Epoch 13/100
188/188 [==============================] - 0s 149us/sample - loss: 0.0045
Epoch 14/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0039
Epoch 15/100
188/188 [==============================] - 0s 133us/sample - loss: 0.0035
Epoch 16/100
188/188 [==============================] - 0s 141us/sample - loss: 0.0034
Epoch 17/100
188/188 [==============================] - 0s 166us/sample - loss: 0.0029
Epoch 18/100
188/188 [==============================] - 0s 164us/sample - loss: 0.0024
Epoch 19/100
188/188 [==============================] - 0s 146us/sample - loss: 0.0021
Epoch 20/100
188/188 [==============================] - 0s 144us/sample - loss: 0.0015
Epoch 21/100
188/188 [==============================] - 0s 124us/sample - loss: 0.0014
Epoch 22/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0011
Epoch 23/100
188/188 [==============================] - 0s 134us/sample - loss: 8.9354e-04
Epoch 24/100
188/188 [==============================] - 0s 155us/sample - loss: 6.6171e-04
Epoch 25/100
188/188 [==============================] - 0s 144us/sample - loss: 4.4529e-04
Epoch 26/100
188/188 [==============================] - 0s 128us/sample - loss: 3.9723e-04
Epoch 27/100
188/188 [==============================] - 0s 129us/sample - loss: 2.9757e-04
Epoch 28/100
188/188 [==============================] - 0s 190us/sample - loss: 2.2500e-04
Epoch 29/100
188/188 [==============================] - 0s 108us/sample - loss: 1.8594e-04
Epoch 30/100
188/188 [==============================] - 0s 158us/sample - loss: 1.7285e-04
Epoch 31/100
188/188 [==============================] - 0s 112us/sample - loss: 1.3853e-04
Epoch 32/100
188/188 [==============================] - 0s 139us/sample - loss: 1.1777e-04
Epoch 33/100
188/188 [==============================] - 0s 135us/sample - loss: 1.2177e-04
Epoch 34/100
188/188 [==============================] - 0s 130us/sample - loss: 1.0908e-04
Epoch 35/100
188/188 [==============================] - 0s 142us/sample - loss: 8.8087e-05
Epoch 36/100
188/188 [==============================] - 0s 154us/sample - loss: 8.2797e-05
Epoch 37/100
188/188 [==============================] - 0s 138us/sample - loss: 7.8728e-05
Epoch 38/100
188/188 [==============================] - 0s 122us/sample - loss: 6.7711e-05
Epoch 39/100
188/188 [==============================] - 0s 148us/sample - loss: 5.5824e-05
Epoch 40/100
188/188 [==============================] - 0s 141us/sample - loss: 5.8234e-05
Epoch 41/100
188/188 [==============================] - 0s 124us/sample - loss: 5.6912e-05
Epoch 42/100
188/188 [==============================] - 0s 162us/sample - loss: 4.5029e-05
Epoch 43/100
188/188 [==============================] - 0s 150us/sample - loss: 4.4958e-05
Epoch 44/100
188/188 [==============================] - 0s 147us/sample - loss: 4.4346e-05
Epoch 45/100
188/188 [==============================] - 0s 102us/sample - loss: 3.6775e-05
Epoch 46/100
188/188 [==============================] - 0s 138us/sample - loss: 3.4327e-05
Epoch 47/100
188/188 [==============================] - 0s 134us/sample - loss: 3.4687e-05
Epoch 48/100
188/188 [==============================] - 0s 119us/sample - loss: 3.6881e-05
Epoch 49/100
188/188 [==============================] - 0s 104us/sample - loss: 4.3608e-05
Epoch 50/100
188/188 [==============================] - 0s 142us/sample - loss: 3.3512e-05
Epoch 51/100
188/188 [==============================] - 0s 128us/sample - loss: 2.5250e-05
Epoch 52/100
188/188 [==============================] - 0s 136us/sample - loss: 2.5939e-05
Epoch 53/100
188/188 [==============================] - 0s 112us/sample - loss: 2.0832e-05
Epoch 54/100
188/188 [==============================] - 0s 123us/sample - loss: 2.1294e-05
Epoch 55/100
188/188 [==============================] - 0s 116us/sample - loss: 2.1837e-05
Epoch 56/100
188/188 [==============================] - 0s 139us/sample - loss: 2.1358e-05
Epoch 57/100
188/188 [==============================] - 0s 121us/sample - loss: 2.3305e-05
Epoch 58/100
188/188 [==============================] - 0s 138us/sample - loss: 2.1387e-05
Epoch 59/100
188/188 [==============================] - 0s 110us/sample - loss: 1.8332e-05
Epoch 60/100
188/188 [==============================] - 0s 94us/sample - loss: 1.7871e-05
Epoch 61/100
188/188 [==============================] - 0s 108us/sample - loss: 1.4429e-05
Epoch 62/100
188/188 [==============================] - 0s 122us/sample - loss: 1.3391e-05
Epoch 63/100
188/188 [==============================] - 0s 123us/sample - loss: 1.3139e-05
Epoch 64/100
188/188 [==============================] - 0s 121us/sample - loss: 1.3726e-05
Epoch 65/100
188/188 [==============================] - 0s 114us/sample - loss: 1.2503e-05
Epoch 66/100
188/188 [==============================] - 0s 114us/sample - loss: 1.2002e-05
Epoch 67/100
188/188 [==============================] - 0s 119us/sample - loss: 1.1698e-05
Epoch 68/100
188/188 [==============================] - 0s 138us/sample - loss: 1.1984e-05
Epoch 69/100
188/188 [==============================] - 0s 127us/sample - loss: 1.1745e-05
Epoch 70/100
188/188 [==============================] - 0s 116us/sample - loss: 1.1986e-05
Epoch 71/100
188/188 [==============================] - 0s 115us/sample - loss: 1.0334e-05
Epoch 72/100
188/188 [==============================] - 0s 117us/sample - loss: 1.0064e-05
Epoch 73/100
188/188 [==============================] - 0s 114us/sample - loss: 1.0704e-05
Epoch 74/100
188/188 [==============================] - 0s 107us/sample - loss: 9.7205e-06
Epoch 75/100
188/188 [==============================] - 0s 112us/sample - loss: 8.7328e-06
Epoch 76/100
188/188 [==============================] - 0s 121us/sample - loss: 8.8889e-06
Epoch 77/100
188/188 [==============================] - 0s 114us/sample - loss: 8.7837e-06
Epoch 78/100
188/188 [==============================] - 0s 116us/sample - loss: 1.0107e-05
Epoch 79/100
188/188 [==============================] - 0s 127us/sample - loss: 1.4341e-05
Epoch 80/100
188/188 [==============================] - 0s 112us/sample - loss: 1.1890e-05
Epoch 81/100
188/188 [==============================] - 0s 119us/sample - loss: 9.9574e-06
Epoch 82/100
188/188 [==============================] - 0s 114us/sample - loss: 1.1788e-05
Epoch 83/100
188/188 [==============================] - 0s 110us/sample - loss: 1.1259e-05
Epoch 84/100
188/188 [==============================] - 0s 135us/sample - loss: 1.1053e-05
Epoch 85/100
188/188 [==============================] - 0s 123us/sample - loss: 1.9915e-05
Epoch 86/100
188/188 [==============================] - 0s 137us/sample - loss: 3.5712e-05
Epoch 87/100
188/188 [==============================] - 0s 111us/sample - loss: 2.6521e-05
Epoch 88/100
188/188 [==============================] - 0s 126us/sample - loss: 2.0526e-05
Epoch 89/100
188/188 [==============================] - 0s 108us/sample - loss: 1.8689e-05
Epoch 90/100
188/188 [==============================] - 0s 120us/sample - loss: 1.1265e-05
Epoch 91/100

188/188 [==============================] - 0s 121us/sample - loss: 6.6571e-06
Epoch 92/100
188/188 [==============================] - 0s 131us/sample - loss: 6.8619e-06
Epoch 93/100
188/188 [==============================] - 0s 104us/sample - loss: 6.1028e-06
Epoch 94/100
188/188 [==============================] - 0s 110us/sample - loss: 6.0003e-06
Epoch 95/100
188/188 [==============================] - 0s 100us/sample - loss: 6.5081e-06
Epoch 96/100
188/188 [==============================] - 0s 103us/sample - loss: 6.6459e-06
Epoch 97/100
188/188 [==============================] - 0s 116us/sample - loss: 6.6287e-06
Epoch 98/100
188/188 [==============================] - 0s 110us/sample - loss: 5.4135e-06
Epoch 99/100
188/188 [==============================] - 0s 103us/sample - loss: 1.0080e-05
Epoch 100/100
188/188 [==============================] - 0s 129us/sample - loss: 1.1945e-05

In [110]:
# Evaluate the model using the test data - mean
#model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")
model_loss = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}")

63/1 - 0s - loss: 4.4030e-04
Loss: 0.0004222245858280018

In [111]:
#y_pred.shape
y_pred_all.shape

(251, 1)

In [112]:
#y_pred
y_pred_all

array([[-1.58964758],
       [-1.12100242],
       [-1.35726085],
       [-1.25657413],
       [-0.64620362],
       [-0.5503049 ],
       [-1.72604782],
       [-0.1974124 ],
       [-6.72036843],
       [-0.22425581],
       [-2.11491464],
       [-1.64629897],
       [-3.66201121],
       [-0.74309098],
       [-1.39078771],
       [-2.17057655],
       [-2.10783951],
       [-0.69383598],
       [-0.91145089],
       [-2.12308107],
       [-0.84598435],
       [-1.47492606],
       [-1.03206239],
       [-3.6302961 ],
       [-2.38526447],
       [-0.5503049 ],
       [-2.00015479],
       [-2.29400311],
       [-3.3087262 ],
       [-0.07970087],
       [-1.02115106],
       [-1.45465479],
       [-1.95122789],
       [-2.91210297],
       [-1.17410521],
       [-0.5503049 ],
       [-0.5503049 ],
       [-0.72804411],
       [-1.47573539],
       [-1.05939481],
       [-2.9650484 ],
       [-0.07970087],
       [-0.5503049 ],
       [-2.07175704],
       [-0.79461529],
       [-0.77523346],
       [-3.05024188],
       [-0.88071591],
       [-1.32338729],
       [-3.93163275],
       [-4.05363809],
       [-0.5503049 ],
       [-1.10902102],
       [-0.5503049 ],
       [-0.65905507],
       [-2.29830556],
       [-0.98396972],
       [-3.6911587 ],
       [-0.90628841],
       [-1.19663791],
       [-1.35402618],
       [-0.01060121],
       [-0.78572798],
       [-0.5503049 ],
       [-3.07952919],
       [-1.54564135],
       [-0.07970087],
       [-0.51336568],
       [-0.62822833],
       [-2.61057006],
       [-2.20335244],
       [-0.31500288],
       [-2.29723528],
       [-1.07285953],
       [-0.93587705],
       [-2.0261251 ],
       [-2.95358329],
       [-1.37304803],
       [ 2.73252742],
       [-0.39343689],
       [-1.94401987],
       [-0.78572798],
       [-0.67074427],
       [-0.64669794],
       [ 0.15548009],
       [-0.74309098],
       [-2.91345348],
       [-1.04559717],
       [-3.90993421],
       [-1.33293026],
       [-3.09303946],
       [-0.24429028],
       [-1.78037374],
       [-2.25530585],
       [-1.13032702],
       [-5.7903515 ],
       [-2.13495037],
       [-0.5503049 ],
       [-2.35332951],
       [-0.31500288],
       [-2.24764704],
       [-0.16286258],
       [-0.66801644],
       [-0.47191125],
       [-0.80307377],
       [-3.45574155],
       [-3.72613918],
       [-0.39343689],
       [-2.70053349],
       [-2.3318798 ],
       [-0.5503049 ],
       [-2.44087557],
       [-4.66542695],
       [-3.52491051],
       [-2.68175908],
       [-2.15031034],
       [-2.06650476],
       [-1.19552183],
       [-2.4677783 ],
       [-0.5503049 ],
       [-0.78845581],
       [-1.21300241],
       [-0.5503049 ],
       [-0.31741705],
       [-0.5503049 ],
       [-2.03252217],
       [-0.07970087],
       [-1.12180995],
       [-2.24946838],
       [-1.45973672],
       [-0.76251392],
       [ 2.73252742],
       [-1.96135212],
       [-2.8329698 ],
       [-3.06306791],
       [-1.14332366],
       [-0.90520775],
       [-1.569542  ],
       [-0.5503049 ],
       [-1.08857346],
       [ 0.22470081],
       [-1.85943642],
       [-0.64669794],
       [-0.07970087],
       [-2.64443051],
       [-0.5503049 ],
       [-0.77423013],
       [-1.57843391],
       [-3.73089907],
       [-1.77661681],
       [ 0.99970652],
       [-3.72297516],
       [-0.07970087],
       [-2.11218279],
       [-2.45602616],
       [-0.5503049 ],
       [-2.37163896],
       [-1.07698183],
       [-0.5503049 ],
       [-1.95716092],
       [-1.35959461],
       [-0.5503049 ],
       [-2.62381444],
       [-2.94533016],
       [-1.74790173],
       [-1.8216147 ],
       [-2.23339456],
       [-1.40919669],
       [-6.60664134],
       [-1.34783383],
       [-0.87800561],
       [-0.3509613 ],
       [-1.71963104],
       [-2.01928363],
       [-1.6664589 ],
       [-0.33505738],
       [-3.18858329],
       [-2.8042662 ],
       [-0.98703601],
       [-1.77336183],
       [-0.43271442],
       [-2.13117262],
       [-1.40106109],
       [-2.0543365 ],
       [-2.3387876 ],
       [-2.68344925],
       [-2.15395604],
       [-0.5503049 ],
       [-1.03206239],
       [-0.79118365],
       [-2.99746431],
       [-1.73383386],
       [-1.09865718],
       [-0.67074427],
       [ 0.04753545],
       [-5.60436203],
       [-4.60703558],
       [-3.99872596],
       [-0.76881415],
       [-1.96344821],
       [-3.0168999 ],
       [-3.94699202],
       [-0.5503049 ],
       [-0.37359053],
       [-1.26196002],
       [-3.7701707 ],
       [-2.43865376],
       [-0.08112531],
       [-1.66771214],
       [-2.5491132 ],
       [-2.12612396],
       [-0.79118365],
       [-0.23656888],
       [-4.65655019],
       [-0.5503049 ],
       [-0.64669794],
       [-1.13032702],
       [-0.5503049 ],
       [-6.42917682],
       [-1.41457387],
       [-0.87969262],
       [-1.30797309],
       [-4.36144248],
       [-0.5503049 ],
       [-3.019682  ],
       [-1.39087021],
       [-2.55889321],
       [-0.98703601],
       [-0.27248694],
       [-3.41790335],
       [-3.87195379],
       [-1.98924844],
       [-2.54665515],
       [-1.20743946],
       [-0.58622296],
       [-0.5503049 ],
       [-2.47627063],
       [-1.77317219],
       [-1.03254663],
       [-2.67412753],
       [-1.89191146],
       [-2.58685844],
       [-1.5440582 ],
       [-2.67630846],
       [-2.79945798],
       [-0.78572798],
       [-0.71639461],
       [-0.91054161],
       [-1.0422809 ],
       [-0.93587705],
       [-0.5503049 ]])

In [113]:
#np.rint(y_pred)
y_pred_all_clean = np.rint(y_pred_all)
y_pred_all_clean

array([[-2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-2.],
       [-0.],
       [-7.],
       [-0.],
       [-2.],
       [-2.],
       [-4.],
       [-1.],
       [-1.],
       [-2.],
       [-2.],
       [-1.],
       [-1.],
       [-2.],
       [-1.],
       [-1.],
       [-1.],
       [-4.],
       [-2.],
       [-1.],
       [-2.],
       [-2.],
       [-3.],
       [-0.],
       [-1.],
       [-1.],
       [-2.],
       [-3.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-3.],
       [-0.],
       [-1.],
       [-2.],
       [-1.],
       [-1.],
       [-3.],
       [-1.],
       [-1.],
       [-4.],
       [-4.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-2.],
       [-1.],
       [-4.],
       [-1.],
       [-1.],
       [-1.],
       [-0.],
       [-1.],
       [-1.],
       [-3.],
       [-2.],
       [-0.],
       [-1.],
       [-1.],
       [-3.],
       [-2.],
       [-0.],
       [-2.],
       [-1.],
       [-1.],
       [-2.],
       [-3.],
       [-1.],
       [ 3.],
       [-0.],
       [-2.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [-1.],
       [-3.],
       [-1.],
       [-4.],
       [-1.],
       [-3.],
       [-0.],
       [-2.],
       [-2.],
       [-1.],
       [-6.],
       [-2.],
       [-1.],
       [-2.],
       [-0.],
       [-2.],
       [-0.],
       [-1.],
       [-0.],
       [-1.],
       [-3.],
       [-4.],
       [-0.],
       [-3.],
       [-2.],
       [-1.],
       [-2.],
       [-5.],
       [-4.],
       [-3.],
       [-2.],
       [-2.],
       [-1.],
       [-2.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-0.],
       [-1.],
       [-2.],
       [-0.],
       [-1.],
       [-2.],
       [-1.],
       [-1.],
       [ 3.],
       [-2.],
       [-3.],
       [-3.],
       [-1.],
       [-1.],
       [-2.],
       [-1.],
       [-1.],
       [ 0.],
       [-2.],
       [-1.],
       [-0.],
       [-3.],
       [-1.],
       [-1.],
       [-2.],
       [-4.],
       [-2.],
       [ 1.],
       [-4.],
       [-0.],
       [-2.],
       [-2.],
       [-1.],
       [-2.],
       [-1.],
       [-1.],
       [-2.],
       [-1.],
       [-1.],
       [-3.],
       [-3.],
       [-2.],
       [-2.],
       [-2.],
       [-1.],
       [-7.],
       [-1.],
       [-1.],
       [-0.],
       [-2.],
       [-2.],
       [-2.],
       [-0.],
       [-3.],
       [-3.],
       [-1.],
       [-2.],
       [-0.],
       [-2.],
       [-1.],
       [-2.],
       [-2.],
       [-3.],
       [-2.],
       [-1.],
       [-1.],
       [-1.],
       [-3.],
       [-2.],
       [-1.],
       [-1.],
       [ 0.],
       [-6.],
       [-5.],
       [-4.],
       [-1.],
       [-2.],
       [-3.],
       [-4.],
       [-1.],
       [-0.],
       [-1.],
       [-4.],
       [-2.],
       [-0.],
       [-2.],
       [-3.],
       [-2.],
       [-1.],
       [-0.],
       [-5.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-6.],
       [-1.],
       [-1.],
       [-1.],
       [-4.],
       [-1.],
       [-3.],
       [-1.],
       [-3.],
       [-1.],
       [-0.],
       [-3.],
       [-4.],
       [-2.],
       [-3.],
       [-1.],
       [-1.],
       [-1.],
       [-2.],
       [-2.],
       [-1.],
       [-3.],
       [-2.],
       [-3.],
       [-2.],
       [-3.],
       [-3.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [114]:
y_pred_all_clean[y_pred_all_clean <= 0] = 0
y_pred_all_clean

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [115]:
forward_players['Pred_red'] = y_pred_all_clean
forward_players

                Pred_red
Player
Aaron Connolly       0.0
Aaron Lennon         0.0
Aaron Mooy           0.0
Adam Idah            0.0
Adam Lallana         0.0
...                  ...
Yoshinori Mut≈ç       0.0
Yves Bissouma        0.0
√ârik Lamela          0.0
√âtienne Capoue       0.0
ƒ∞lkay G√ºndoƒüan       0.0

[251 rows x 1 columns]

In [116]:
pred_red_df = forward_players
pred_red_df

                Pred_red
Player
Aaron Connolly       0.0
Aaron Lennon         0.0
Aaron Mooy           0.0
Adam Idah            0.0
Adam Lallana         0.0
...                  ...
Yoshinori Mut≈ç       0.0
Yves Bissouma        0.0
√ârik Lamela          0.0
√âtienne Capoue       0.0
ƒ∞lkay G√ºndoƒüan       0.0

[251 rows x 1 columns]

In [117]:
#clean_player_df.to_csv('cleaned_players.csv', index = False)
pred_red_df.to_csv('pred_red.csv')

In [118]:
y_pred_nn = nn.predict(X_test_scaled)#X_scaler.transform(X))
y_pred_nn
pd.DataFrame({'y_pred_nn': y_pred_nn[:,0], 'y_test': y_test[:,0]})

    y_pred_nn  y_test
0    0.003431     0.0
1    0.002414     0.0
2   -0.007269     0.0
3   -0.002650     0.0
4    0.007643     0.0
..        ...     ...
58  -0.023880     0.0
59  -0.005282     0.0
60   0.033011     0.0
61  -0.008247     0.0
62   0.022992     0.0

[63 rows x 2 columns]